/* Kosha Wealth — logged-in app: shell + core screens */
(function (K) {
  const { $, $$, ico, inr, L, pc, F, GOALS } = K;
  const A = K.A = { cart: new Map(), newUser: false, V: {}, ex: { c: 'All', risk: new Set(), amc: new Set(), q: '', s: 'r3' }, cmp: new Set() };
  const gName = id => GOALS.find(g => g.id === id).name, gCol = id => GOALS.find(g => g.id === id).color; A.gName = gName;
  const H = [[F[0], 180000, 231400, 'wealth'], [F[8], 120000, 146900, 'edu'], [F[22], 90000, 96300, 'emg'], [F[19], 80000, 99800, 'edu'], [F[27], 60000, 64900, 'wealth']]; A.H = H;
  const INV = H.reduce((s, h) => s + h[1], 0), CUR = H.reduce((s, h) => s + h[2], 0);
  const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const ah = (t, sub, right = '') => `<div class="ah"><div><h1>${t}</h1>${sub ? `<p class="sub">${sub}</p>` : ''}</div>${right ? `<div class="ah-r">${right}</div>` : ''}</div>`;
  A.ah = ah;
  const SN = [['Your money', [['overview', 'Overview', 'home'], ['mf/portfolio', 'Portfolio', 'pie'], ['networth', 'Net worth', 'layers']]], ['Invest', [['mf/invest', 'Mutual funds', 'chart'], ['bonds', 'Bonds', 'bank'], ['fd', 'Fixed deposits', 'coin'], ['nps', 'NPS', 'sunrise'], ['sif', 'SIF', 'bolt', 'New'], ['equity', 'Stocks', 'trend'], ['insurance', 'Insurance', 'shield']]], ['Tools', [['calc', 'Calculators', 'refresh'], ['reports', 'Reports', 'doc'], ['help', 'Help', 'chat']]]];
  const MF = [['portfolio', 'Portfolio'], ['invest', 'Invest'], ['explore', 'All funds'], ['transactions', 'Transactions']];

  /* ---------- fund rows ---------- */
  A.fundRows = (list, o = {}) => {
    if (!list.length) return `<div class="none"><h3 class="serif" style="font-size:1.5rem">No funds match</h3><p>Try removing a filter.</p></div>`;
    return `<div class="fr hd"><span>Fund</span><span class="c0">Trend</span><span class="r c1">1 yr</span><span class="r">3 yr</span><span class="r c5">5 yr</span><span></span></div>` + list.map(f => `<div class="fr n"><div class="nm">${o.cmp ? `<label class="cmpb" title="Compare"><input type="checkbox" data-cmp="${f.id}" ${A.cmp.has(f.id) ? 'checked' : ''} aria-label="Compare ${f.name}"></label>` : ''}<div><button data-f="${f.id}">${f.name}</button><small><span class="pill">${f.cat}</span>${K.rate(f.rating)}</small></div></div><span class="sp c0">${K.spark(K.sparkFor(f), { w: 80, h: 28 })}</span><span class="r c1">${pc(f.r1)}</span><span class="r">${pc(f.r3)}</span><span class="r c5">${pc(f.r5)}</span><button class="addb ${A.cart.has(f.id) ? 'on' : ''}" data-add="${f.id}">${A.cart.has(f.id) ? 'Added' : 'Add'}</button></div>`).join('');
  };

  /* ---------- portfolio series ---------- */
  const pfSeries = rg => { const m = { '6M': 6, '1Y': 12, '3Y': 36, All: 48 }[rg], a = { '6M': .94, '1Y': .85, '3Y': .55, All: .25 }[rg], v = [], iv = [], lab = [], gain = CUR / INV - 1;
    for (let i = 0; i <= m; i++) { const inv = INV * (a + (1 - a) * i / m), g = gain * Math.pow(i / m, 1.15) + (i && i < m ? Math.sin(i * .9) * .012 + (i % 7 === 3 ? -.02 : 0) : 0); iv.push(inv); v.push(inv * (1 + g)); const d = new Date(2026, 9 - (m - i), 1); lab.push(MON[d.getMonth()] + ' ' + String(d.getFullYear()).slice(2)) } return { v, iv, lab } };

  /* =============== OVERVIEW =============== */
  A.V.overview = () => {
    const top = A.newUser ? `<div class="onb"><div class="onb-l"><span class="pill gold">${ico('sparkle')} Welcome, Ravi</span><h2 class="serif">Your KYC is done. Let’s put your first goal to work.</h2><p>Pick a goal and we will suggest funds and a monthly amount, or browse funds yourself. Your advisor Priya is a call away either way.</p><div class="acts"><a class="b b-go b-lg" href="#/app/mf/invest">Start investing${ico('arrow', 'go')}</a><a class="b b-line b-lg" href="#/goals">Plan a goal first</a></div></div>
      <div class="onb-r"><h4>Get set up</h4><div class="prog"><i style="width:25%"></i></div>${[['KYC verified', 'Done on 6 Oct', 1, '#/app/kyc'], ['Add a nominee', 'Takes 2 minutes', 0, '#/app/profile/nominee'], ['Take the risk quiz', 'Six questions', 0, '#/app/profile/risk'], ['Set up autopay', 'For your SIPs', 0, '#/app/profile/bank']].map(s => `<a class="stp ${s[2] ? 'done' : ''}" href="${s[3]}"><span class="ck">${s[2] ? ico('check') : ''}</span><span><b>${s[0]}</b><small>${s[1]}</small></span>${s[2] ? '' : ico('chevR')}</a>`).join('')}</div></div>`
      : `<div class="ovg"><div class="ov-hero dark"><div class="ov-t"><div><p class="greet">Good evening, Ravi. Here is where things stand.</p><div class="tot n serif" id="ovT">${inr(CUR)}</div><p class="chg n"><span class="up">+${inr(CUR - INV)} overall</span> · on ${inr(INV)} invested</p></div><div class="seg" id="ovR">${['6M', '1Y', '3Y', 'All'].map((r, i) => `<button data-r="${r}" aria-pressed="${r === '3Y'}">${r}</button>`).join('')}</div></div><div id="ovC"></div><div class="legend" style="margin-top:6px"><span><i style="background:#7FD8E0"></i>Value</span><span><i style="background:#E8A317"></i>Invested</span></div></div>
      <div class="ov-s"><div class="mt"><small>Today</small><b class="up n">+₹2,140</b><span class="pill up">+0.38%</span></div><div class="mt"><small>Returns per year (XIRR)</small><div class="mt-r"><span class="ringv">${K.ring(.74, { size: 64, thick: 7, c: 'var(--teal)' })}<div class="n" style="font-size:.8rem;font-weight:800;color:var(--ink)">14.8%</div></span><span class="sm muted">vs 12.2% for the Nifty 50 TRI</span></div></div><div class="mt nx"><div class="dt"><b>5</b><small>NOV</small></div><div><small>Next SIP</small><b class="n">₹10,000</b><span class="sm muted">+ ₹15,000 across 3 funds</span></div></div></div></div>`;
    return `${ah('Overview', '', `<div class="seg" id="nu"><button data-n="0" aria-pressed="${!A.newUser}">Existing investor</button><button data-n="1" aria-pressed="${A.newUser}">New investor</button></div>`)}
 ${top}
 <div class="flag">${ico('info')}<div><b>No nominee added yet.</b> <span class="muted">Without one, your family will need extra paperwork to claim these investments.</span></div><a class="b b-ink b-sm" href="#/app/profile/nominee">Add a nominee</a></div>
 ${A.newUser ? '' : `<section><div class="ph2"><h3>Your goals</h3><a class="lnk" href="#/app/mf/portfolio">Manage goals ${ico('arrow')}</a></div><div class="grings">${[['edu', 246700, 15e5, 'On track', 1], ['ret', 121350, 2e7, 'Needs ₹4,000 more a month', 0], ['emg', 96300, 3e5, 'On track', 1], ['wealth', 296300, 0, 'No end date', 1]].map(g => { const p = g[2] ? Math.min(1, g[1] / g[2]) : 0; return `<a class="gr2" href="#/app/mf/portfolio"><span class="ringv">${K.ring(g[2] ? p : 1, { size: 96, thick: 9, c: gCol(g[0]), track: g[2] ? 'var(--rule)' : 'color-mix(in srgb,' + gCol(g[0]) + ' 25%,transparent)' })}<div>${ico(GOALS.find(x => x.id === g[0]).icon)}</div></span><b>${gName(g[0])}</b><span class="n">${L(g[1])}${g[2] ? ` <small class="muted">of ${L(g[2])}</small>` : ''}</span><span class="pill ${g[4] ? 'up' : 'gold'}">${g[3]}</span></a>` }).join('')}</div></section>
 <div class="two"><div class="panel pp"><div class="ph2"><h3>Where your money is</h3><span class="fine">As of today</span></div><div class="alloc"><div class="ringv">${K.donut([['Equity', 72, '#2F3A9E'], ['Debt', 18, '#9AA1D8'], ['Gold', 6, '#E8A317'], ['Cash', 4, '#C9CCD9']], { size: 168, thick: 24 })}<div><b class="n serif" style="font-size:1.8rem;color:var(--ink)">72%</b><small class="muted">equity</small></div></div><div class="alg">${[['Equity', 72, '#2F3A9E'], ['Debt', 18, '#9AA1D8'], ['Gold', 6, '#E8A317'], ['Cash', 4, '#C9CCD9']].map(a => `<div><span><i style="background:${a[2]}"></i>${a[0]}</span><b class="n">${a[1]}%</b></div>`).join('')}<p class="sm" style="margin-top:10px">Equity is 7 points above your target. <b style="color:var(--ink)">Priya will suggest a rebalance at your next review.</b></p></div></div></div>
 <div class="panel pp"><div class="ph2"><h3>Next 30 days</h3></div><div class="tlv">${[['5 Nov', 'SIP debit · ₹10,000', 'Arya Flexi Cap', 'refresh'], ['5 Nov', 'SIP debit · ₹5,000', 'Kaveri Mid Cap', 'refresh'], ['14 Nov', 'Quarterly review', 'Call with Priya · 3:00 pm', 'phone'], ['30 Nov', 'Add a nominee', 'Reminder', 'flag']].map(t => `<div><span class="ic">${ico(t[3])}</span><span><b>${t[1]}</b><small>${t[0]} · ${t[2]}</small></span></div>`).join('')}</div></div></div>`}
 <section><div class="ph2"><h3>Ways to invest</h3></div><div class="strip">${[['mf/invest', 'Mutual funds', '1,500+ funds', 'chart'], ['bonds', 'Bonds', 'Fixed income', 'bank'], ['fd', 'Fixed deposits', 'Rated issuers', 'coin'], ['nps', 'NPS', 'Retirement', 'sunrise'], ['sif', 'SIF', 'From ₹10 L', 'bolt', 'New'], ['equity', 'Stocks', 'Trading account', 'trend']].map(p => `<a href="#/app/${p[0]}"><span class="ic">${ico(p[3])}</span><b>${p[1]}</b><span>${p[2]}</span>${p[4] ? `<span class="tag">${p[4]}</span>` : ''}</a>`).join('')}</div></section>
 <div class="two"><div class="panel pp"><div class="ph2"><h3>Funds our research team likes right now</h3><a class="lnk" href="#/app/mf/explore">All funds ${ico('arrow')}</a></div><div class="chips" id="col" style="margin-bottom:8px">${['Most chosen', 'Best 3 years', 'Tax saving', 'Gold'].map((c, i) => `<button class="chip" data-c="${i}" aria-pressed="${i === 0}">${c}</button>`).join('')}</div><div id="colL"></div></div>
 <div class="stk2"><div class="panel pp nwc"><span class="ic">${ico('layers')}</span><h3 class="serif">See everything you own</h3><p>Link bank accounts, other mutual funds, stocks and NPS through the RBI Account Aggregator network. You choose what to share.</p><a class="b b-gold b-sm" href="#/app/networth">Check my net worth</a></div>
 <div class="panel pp"><div class="ph2"><h3>Latest from research</h3></div><div class="rl3">${K.ARTICLES.slice(0, 3).map(r => `<a href="#/research/read/${r.id}"><b>${r.title}</b><small>${r.date} · ${r.mins} min</small></a>`).join('')}</div></div></div></div>`;
  };
  A.wire_overview = () => {
    $$('#nu button').forEach(b => b.onclick = () => { A.newUser = b.dataset.n === '1'; A.render() });
    if ($('#ovC')) { const draw = rg => { const s = pfSeries(rg); K.chart($('#ovC'), { h: 250, series: [{ name: 'Value', data: s.v, color: '#7FD8E0', fill: 'rgba(127,216,224,.2)' }, { name: 'Invested', data: s.iv, color: '#E8A317', dash: '5 5' }], x: i => s.lab[i], xticks: 5, fmt: K.L, yfmt: K.short }); const e = $('#ovC'); e.classList.remove('st'); e._drawn = false }; draw('3Y'); $('#ovR').onclick = e => { const b = e.target.closest('button'); if (!b) return; $$('#ovR button').forEach(x => x.setAttribute('aria-pressed', x === b)); draw(b.dataset.r) } }
    const sets = [F.filter(f => f.rating >= 3 && f.cat !== 'Liquid').sort((a, b) => b.inv - a.inv), F.filter(f => f.cat !== 'Liquid').sort((a, b) => b.r3 - a.r3), F.filter(f => f.cat === 'ELSS'), F.filter(f => f.cat === 'Gold')];
    const s = i => $('#colL').innerHTML = A.fundRows(sets[i].slice(0, 5)); $$('#col .chip').forEach(c => c.onclick = () => { $$('#col .chip').forEach(x => x.setAttribute('aria-pressed', x === c)); s(+c.dataset.c) }); s(0);
  };

  /* =============== PORTFOLIO =============== */
  let pt = 'Summary', prg = '3Y';
  A.V['mf/portfolio'] = () => `${ah('Mutual fund portfolio', 'Ravi Kumar, all folios', `<a class="b b-go b-sm" href="#/app/mf/invest">Start a SIP</a><a class="b b-line b-sm" href="#/app/mf/invest">Invest a lump sum</a>`)}
 <div class="mx n"><div><small>Invested</small><b>${inr(INV)}</b></div><div><small>Current value</small><b>${inr(CUR)}</b><em class="up">+₹2,140 today</em></div><div><small>Overall gain</small><b class="up">+${inr(CUR - INV)}</b><em class="up">+${((CUR - INV) / INV * 100).toFixed(1)}%</em></div><div><small>Returns per year</small><b>14.8%</b><em class="muted">XIRR</em></div></div>
 <div class="ptabs" id="pt">${['Summary', 'Performance', 'What you own', 'Capital gains', 'Held elsewhere'].map(t => `<button aria-pressed="${pt === t}">${t}</button>`).join('')}</div><div id="pb">${pbody()}</div>`;
  function pbody() {
    if (pt === 'Summary') { const gs = ['wealth', 'edu', 'emg', 'ret'].map(g => { const hs = H.filter(h => h[3] === g); return [g, hs.reduce((s, h) => s + h[2], 0), hs.reduce((s, h) => s + h[1], 0), hs.length] });
      return `<div class="two"><div class="panel pp"><div class="ph2"><h3>By goal</h3><button class="lnk" data-toast="New goal portfolio created (demo)">Create a goal ${ico('plus')}</button></div><div class="alloc"><div class="ringv">${K.donut(gs.filter(g => g[1]).map(g => [gName(g[0]), g[1], gCol(g[0])]), { size: 176, thick: 24 })}<div><b class="n serif" style="font-size:1.5rem;color:var(--ink)">${K.L(CUR)}</b><small class="muted">total</small></div></div><div class="alg">${gs.map(g => `<div><span><i style="background:${gCol(g[0])}"></i>${gName(g[0])}<small class="muted" style="display:block;margin-left:19px">${g[3] ? g[3] + ' fund' + (g[3] > 1 ? 's' : '') : 'Nothing invested yet'}</small></span><b class="n">${g[1] ? L(g[1]) : '—'}${g[1] ? '<small style="display:block;font-weight:600">' + pc((g[1] - g[2]) / g[2] * 100) + '</small>' : ''}</b></div>`).join('')}</div></div></div>
      <div class="panel pp"><div class="ph2"><h3>Asset mix</h3></div><div class="mixbar">${[['Equity', 72, '#2F3A9E'], ['Debt', 18, '#9AA1D8'], ['Gold', 6, '#E8A317'], ['Cash', 4, '#C9CCD9']].map(m => `<div style="width:${m[1]}%;background:${m[2]}">${m[1] > 8 ? m[1] + '%' : ''}</div>`).join('')}</div><p class="sm muted" style="margin-top:14px">Recommended for you: 65% equity, 25% debt, 10% gold</p></div></div>
      <div class="panel pp"><div class="ph2"><h3>Your funds</h3></div><div class="tbl"><table class="t n" style="min-width:760px"><thead><tr><th>Fund</th><th>Goal</th><th>Trend</th><th class="r">Invested</th><th class="r">Value</th><th class="r">Gain</th><th></th></tr></thead><tbody>${H.map(([f, i, c, g]) => `<tr><td><button class="fb" data-f="${f.id}">${f.name}</button></td><td><span class="gdot"><i style="background:${gCol(g)}"></i>${gName(g)}</span></td><td>${K.spark(K.sparkFor(f), { w: 70, h: 24 })}</td><td class="r">${inr(i)}</td><td class="r">${inr(c)}</td><td class="r">${pc((c - i) / i * 100)}</td><td class="r"><span style="display:inline-flex;gap:14px"><button class="lnk" data-f="${f.id}">Invest more</button><button class="lnk" style="color:var(--muted)" data-toast="Redemption flow opens here (demo)">Withdraw</button></span></td></tr>`).join('')}</tbody></table></div></div>` }
    if (pt === 'Performance') return `<div class="panel pp"><div class="ph2"><h3>Value against what you have put in</h3><div class="seg" id="prg">${['1Y', '3Y', 'All'].map(r => `<button data-r="${r}" aria-pressed="${r === prg}">${r}</button>`).join('')}</div></div><div id="pc"></div><div class="legend" style="margin-top:8px"><span><i style="background:var(--teal)"></i>Portfolio value</span><span><i style="background:var(--gold)"></i>Amount invested</span></div></div>
      <div class="panel pp"><div class="ph2"><h3>Against the market</h3></div><table class="t n"><thead><tr><th>Period</th><th class="r">Your portfolio</th><th class="r">Nifty 50 TRI</th><th class="r">Difference</th></tr></thead><tbody>${[['1 year', 8.4, 6.1], ['3 years, per year', 14.8, 12.2], ['Since you started, per year', 15.6, 13.1]].map(r => `<tr><td>${r[0]}</td><td class="r">${pc(r[1])}</td><td class="r">${pc(r[2])}</td><td class="r"><span class="pill up">+${(r[1] - r[2]).toFixed(1)} pts</span></td></tr>`).join('')}</tbody></table></div>`;
    if (pt === 'What you own') return `<div class="two"><div class="panel pp"><div class="ph2"><h3>Inside your equity</h3></div>${[['Large companies', 54], ['Mid-sized', 28], ['Small companies', 18]].map(r => `<div class="hb"><span>${r[0]}</span><div class="bar"><span style="width:${r[1]}%"></span></div><b class="n">${r[1]}%</b></div>`).join('')}<h3 style="margin:28px 0 10px;font-size:1rem">Biggest sectors</h3>${[['Banks and finance', 27], ['IT services', 14], ['Consumer goods', 11], ['Healthcare', 8], ['Energy', 7]].map(r => `<div class="hb"><span>${r[0]}</span><div class="bar"><span style="width:${r[1] * 3}%;background:var(--gold)"></span></div><b class="n">${r[1]}%</b></div>`).join('')}</div>
      <div class="panel pp"><div class="ph2"><h3>Top holdings</h3></div>${[['HDFC-type Bank', 6.4], ['Infosys-type IT', 4.8], ['Reliance-type Energy', 4.1], ['ICICI-type Bank', 3.9], ['Titan-type Consumer', 2.6]].map((r, i) => `<div class="hb"><span>${r[0].replace('-type', ' (sample)')}</span><div class="bar"><span style="width:${r[1] * 14}%"></span></div><b class="n">${r[1]}%</b></div>`).join('')}<p class="fine" style="margin-top:14px">Sample holdings across your funds, combined.</p></div></div>`;
    if (pt === 'Capital gains') return `<div class="panel pp"><div class="ph2"><div class="seg"><button aria-pressed="true">This year, 2026–27</button><button aria-pressed="false">Last year</button></div><button class="lnk" data-toast="Statement downloaded (demo)">Download statement ${ico('download')}</button></div><div class="cgs">${[['Booked, short term', '₹0', ''], ['Booked, long term', '₹0', ''], ['On paper, short term', '+₹18,240', 'up'], ['On paper, long term', '+₹74,860', 'up']].map(c => `<div><small>${c[0]}</small><b class="n ${c[2]}">${c[1]}</b></div>`).join('')}</div><div class="flag">${ico('sparkle')}<div><b>₹1,25,000 of long-term gains can still be booked tax-free this year.</b> <span class="muted">Ask Priya whether it is worth doing.</span></div></div><p class="fine" style="margin-top:14px">Indicative figures, not tax advice.</p></div>`;
    return `<div class="panel onb" style="grid-template-columns:1fr"><div class="onb-l"><h2 class="serif">Funds you bought somewhere else</h2><p>Import your consolidated account statement (CAS) to see every mutual fund you own, from any platform, next to your Kosha investments. We only read it; nothing moves.</p><div class="acts"><button class="b b-go" data-toast="CAS fetch with email OTP (demo)">Import with email OTP</button><button class="b b-line" data-toast="Upload CAS PDF (demo)">Upload a CAS PDF</button></div></div></div>`;
  }
  A.wire_portfolio = () => { $$('#pt button').forEach(b => b.onclick = () => { pt = b.textContent; A.render() }); if ($('#pc')) { const d = rg => { const s = pfSeries(rg); K.chart($('#pc'), { h: 280, series: [{ name: 'Value', data: s.v, color: 'var(--teal)', fill: 'color-mix(in srgb,var(--teal) 12%,transparent)' }, { name: 'Invested', data: s.iv, color: 'var(--gold)', dash: '6 5' }], x: i => s.lab[i], xticks: 6, fmt: K.L, yfmt: K.short }); $('#pc')._drawn = false }; d(prg); $('#prg').onclick = e => { const b = e.target.closest('button'); if (!b) return; prg = b.dataset.r; $$('#prg button').forEach(x => x.setAttribute('aria-pressed', x === b)); d(prg) } } };

  /* =============== INVEST =============== */
  A.V['mf/invest'] = () => `${ah('Invest in mutual funds', 'Start a SIP, invest a lump sum, or let us move money for you on a schedule.')}
 <div class="qa">${[['SIP', 'Every month', 'refresh', 'var(--teal)'], ['Lump sum', 'One time', 'wallet', 'var(--gold-2)'], ['Step-up SIP', 'Grows yearly', 'trend', 'var(--violet)'], ['STP', 'Lump sum in stages', 'layers', 'var(--rose)'], ['SWP', 'Monthly income', 'download', 'var(--up)'], ['New fund offers', '3 open now', 'sparkle', 'var(--ink)']].map(t => `<a href="#/app/mf/explore" style="--c:${t[3]}"><span class="ic">${ico(t[2])}</span><b>${t[0]}</b><small>${t[1]}</small></a>`).join('')}</div>
 <div class="panel pp"><div class="ph2"><div><h3>Kosha Select</h3><p class="sm muted" style="margin-top:4px">Eight funds our research team would put its own money in. Reviewed every quarter.</p></div><a class="lnk" href="#/app/mf/explore">All 1,500+ funds ${ico('arrow')}</a></div>${A.fundRows(K.SEL.map(i => F[i - 1]))}</div>
 <section><div class="ph2"><h3>Browse by type</h3></div><div class="types">${['Equity', 'Debt', 'Hybrid', 'ELSS', 'Index', 'Liquid'].map(c => { const rk = { Low: 1, Moderate: 2, High: 3, 'Very high': 4 }[K.RISK[c]]; return `<a href="#/app/mf/explore?c=${c}"><b class="serif">${c}</b><small>${F.filter(f => f.cat === c).length} funds</small><span class="rmeter">${[1, 2, 3, 4].map(i => `<i class="${i <= rk ? 'on' : ''}"></i>`).join('')}</span><span class="sm muted">${K.RISK[c]} risk</span></a>` }).join('')}</div></section>`;

  /* =============== EXPLORE =============== */
  A.V['mf/explore'] = () => { const ex = A.ex; return `${ah('All funds', 'Sample data for the demo. The live site updates prices every evening.')}
 <div class="chips" id="exc">${['All', 'Kosha select', ...K.CATS].map(c => `<button class="chip" data-c="${c}" aria-pressed="${ex.c === c}">${c}</button>`).join('')}</div>
 <div class="ex"><aside class="filt panel pp"><div><h5>Risk</h5>${['Low', 'Moderate', 'High', 'Very high'].map(r => `<label><input type="checkbox" data-r="${r}" ${ex.risk.has(r) ? 'checked' : ''}>${r}</label>`).join('')}</div><div><h5>Fund house</h5>${K.AMCS.map(a => `<label><input type="checkbox" data-a="${a}" ${ex.amc.has(a) ? 'checked' : ''}>${a}</label>`).join('')}</div></aside>
 <div class="panel pp"><div class="srch"><input id="exq" type="search" placeholder="Search by name" value="${K.esc(ex.q)}" aria-label="Search"><select id="exs" aria-label="Sort"><option value="r3">Best 3-year return</option><option value="r1">Best 1-year return</option><option value="r5">Best 5-year return</option><option value="rating">Highest rated</option><option value="aum">Largest</option></select></div><p class="fine" style="margin:4px 0 8px" id="exn"></p><div id="exl"></div></div></div><div class="cmpbar" id="cmpbar"></div>` };
  const exl = () => { const ex = A.ex; let l = F.filter(f => (ex.c === 'All' || (ex.c === 'Kosha select' ? K.SEL.includes(f.id) : f.cat === ex.c)) && (!ex.risk.size || ex.risk.has(f.risk)) && (!ex.amc.size || ex.amc.has(f.amc)) && (!ex.q || f.name.toLowerCase().includes(ex.q.toLowerCase()))); l.sort((a, b) => b[ex.s] - a[ex.s]); $('#exl').innerHTML = A.fundRows(l, { cmp: 1 }); $('#exn').textContent = l.length + ' funds'; cmpBar() };
  const cmpBar = () => { const el = $('#cmpbar'); if (!el) return; el.classList.toggle('show', A.cmp.size > 0); el.innerHTML = `<span><b>${A.cmp.size}</b> selected to compare <small>(up to 3)</small></span><span style="display:flex;gap:10px"><button class="b b-glass b-sm" id="cmpX">Clear</button><button class="b b-gold b-sm" id="cmpGo" ${A.cmp.size < 2 ? 'disabled style="opacity:.5"' : ''}>Compare ${A.cmp.size >= 2 ? '' : '(pick 2+)'}</button></span>`; $('#cmpX').onclick = () => { A.cmp.clear(); exl() }; $('#cmpGo').onclick = openCmp };
  function openCmp() { const fs = [...A.cmp].map(i => F[i - 1]); if (fs.length < 2) return; const m = document.createElement('div'); m.className = 'modal show'; const rows = [['Category', f => `${f.cat}, ${f.sub}`], ['Risk', f => f.risk], ['Rating', f => K.rate(f.rating)], ['1 year', f => pc(f.r1)], ['3 years, yearly', f => pc(f.r3)], ['5 years, yearly', f => pc(f.r5)], ['Yearly cost', f => f.exp + '%'], ['Fund size', f => '₹' + f.aum.toLocaleString('en-IN') + ' Cr'], ['SIP from', f => '₹' + f.minsip], ['Fund manager', f => f.mgr]];
    m.innerHTML = `<div class="mb cmpm"><div class="cmph"><h3 class="serif">Compare funds</h3><button class="x" data-x aria-label="Close">×</button></div><div class="tbl"><table class="t n"><thead><tr><th></th>${fs.map(f => `<th style="text-transform:none;letter-spacing:0;font-size:.95rem;color:var(--ink)">${f.name}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr><td class="muted">${r[0]}</td>${fs.map(f => `<td>${r[1](f)}</td>`).join('')}</tr>`).join('')}<tr><td></td>${fs.map(f => `<td><button class="b b-go b-sm" data-add="${f.id}" data-xc>Add to basket</button></td>`).join('')}</tr></tbody></table></div></div>`; document.body.appendChild(m); $('#scrim').classList.add('show');
    const close = () => { m.remove(); $('#scrim').classList.remove('show') }; m.onclick = e => { if (e.target === m || e.target.closest('[data-x]') || e.target.closest('[data-xc]')) close() } }
  A.wire_explore = () => { const ex = A.ex; $('#exs').value = ex.s; $$('#exc .chip').forEach(c => c.onclick = () => { ex.c = c.dataset.c; $$('#exc .chip').forEach(x => x.setAttribute('aria-pressed', x === c)); exl() });
    $('.filt').onchange = e => { const t = e.target; if (t.dataset.r) t.checked ? ex.risk.add(t.dataset.r) : ex.risk.delete(t.dataset.r); if (t.dataset.a) t.checked ? ex.amc.add(t.dataset.a) : ex.amc.delete(t.dataset.a); exl() };
    $('#exq').oninput = e => { ex.q = e.target.value; exl() }; $('#exs').onchange = e => { ex.s = e.target.value; exl() };
    $('#exl').addEventListener('change', e => { const c = e.target.closest('[data-cmp]'); if (!c) return; const id = +c.dataset.cmp; if (c.checked) { if (A.cmp.size >= 3) { c.checked = false; K.toast('You can compare up to three funds'); return } A.cmp.add(id) } else A.cmp.delete(id); cmpBar() }); exl() };

  /* =============== FUND DETAIL =============== */
  const navPts = (f, d) => { const s = K.navSeries(f, d), st = Math.max(1, Math.floor(s.length / 240)); const out = [], lab = []; for (let i = 0; i < s.length; i += st) { out.push(s[i]); const dt = new Date(2026, 9, 9 - (d - i)); lab.push(dt.getDate() + ' ' + MON[dt.getMonth()] + ' ' + String(dt.getFullYear()).slice(2)) } return { out, lab } };
  A.V.fund = id => { const f = K.fund(id), peers = F.filter(x => x.cat === f.cat).sort((a, b) => b.r5 - a.r5), rk = { Low: 1, Moderate: 2, High: 3, 'Very high': 4 }[f.risk], inB = A.cart.has(f.id),
      sec = f.cat === 'Debt' || f.cat === 'Liquid' ? [['Government securities', 38], ['AAA company bonds', 34], ['Bank certificates', 16], ['Cash', 12]] : [['Banks', 21], ['IT services', 12], ['Automobiles', 8], ['Pharma', 7], ['Consumer goods', 6], ['Energy', 6]], avg = k => peers.reduce((s, p) => s + p[k], 0) / peers.length;
    return `<a href="#/app/mf/explore" class="lnk" style="color:var(--muted)">${ico('chevL')} All funds</a>
 <div class="fd"><div class="fd-m"><div class="fdh"><div class="lg">${f.amc[0]}</div><div><h1>${f.name}</h1><p class="cat"><span class="pill">${f.cat}</span> <span class="pill violet">${f.sub}</span> ${K.rate(f.rating)} <span class="muted sm">${f.amc} Mutual Fund</span></p></div></div>
  <div class="navnow n"><div class="lead"><small>NAV, 9 Oct</small><b>₹${f.nav.toFixed(2)}</b> <span class="up sm" style="font-weight:700">+0.38%</span></div><div><small>Risk</small><b>${f.risk}</b><span class="riskdial">${[1, 2, 3, 4].map(k => `<i style="${k <= rk ? 'background:' + (rk >= 4 ? 'var(--down)' : rk === 3 ? 'var(--gold)' : 'var(--up)') : ''}"></i>`).join('')}</span></div><div><small>Fund size</small><b>₹${f.aum.toLocaleString('en-IN')} Cr</b></div><div><small>Yearly cost</small><b>${f.exp}%</b></div></div>
  <div class="panel pp"><div class="ph2"><h3>Price history</h3><div class="seg" id="rg">${['1Y', '3Y', '5Y'].map((r, i) => `<button data-d="${[365, 1095, 1825][i]}" aria-pressed="${i === 0}">${r}</button>`).join('')}</div></div><div id="cb"></div></div>
  <div class="panel pp"><div class="ph2"><h3>Returns, yearly</h3><span class="fine">Against the average of ${peers.length} ${f.cat.toLowerCase()} funds</span></div><div class="rets n">${[['1 year', 'r1'], ['3 years', 'r3'], ['5 years', 'r5']].map(r => `<div><small>${r[0]}</small><b>${pc(f[r[1]])}</b><span class="sm muted">Category ${avg(r[1]).toFixed(1)}%</span><span class="rbar"><i style="width:${Math.max(4, Math.min(100, f[r[1]] / 22 * 100))}%"></i><em style="left:${Math.max(2, Math.min(98, avg(r[1]) / 22 * 100))}%"></em></span></div>`).join('')}</div></div>
  <div class="panel pp"><div class="ph2"><h3>If you had invested</h3><div class="seg" id="rm"><button data-m="s" aria-pressed="true">Every month</button><button data-m="l" aria-pressed="false">Once</button></div></div><div class="f2c"><div><div class="sl"><div class="top"><label for="ra">Amount</label><span class="val n" id="raL"></span></div><input type="range" id="ra" min="500" max="100000" step="500" value="10000"></div><div class="sl" style="margin:0"><div class="top"><label for="ry">Starting</label><span class="val n" id="ryL"></span></div><input type="range" id="ry" min="1" max="5" value="3"></div></div><div class="dl n" id="ro"></div></div></div>
  <div class="two eq"><div class="panel pp"><h3 style="margin-bottom:4px">What the fund holds</h3><p class="sm muted" style="margin-bottom:14px">${f.cat === 'Debt' || f.cat === 'Liquid' ? 'Debt 92%, cash 8%' : 'Shares 94.2%, debt 1.3%, cash 4.5%'}, as of 30 September</p>${sec.map(s => `<div class="hb"><span>${s[0]}</span><div class="bar"><span style="width:${s[1] * 2.2}%"></span></div><b class="n">${s[1]}%</b></div>`).join('')}</div>
  <div class="panel pp"><h3 style="margin-bottom:8px">The fine print</h3><div class="dl">${[['Exit charge', '1% if sold within a year'], ['Compared against', f.cat === 'Debt' ? 'CRISIL Composite Bond' : 'Nifty 500 TRI'], ['Fund manager', f.mgr], ['Running since', f.age + ' years'], ['Lock-in', f.cat === 'ELSS' ? '3 years' : 'None'], ['Plan', 'Regular, growth']].map(d => `<div><small>${d[0]}</small><b>${d[1]}</b></div>`).join('')}</div><div style="display:flex;gap:20px;margin-top:18px"><button class="lnk" data-toast="Scheme document opens (demo)">Scheme document</button><button class="lnk" data-toast="Factsheet opens (demo)">Factsheet</button></div></div></div>
  <div class="panel pp"><div class="ph2"><h3>Other ${f.cat.toLowerCase()} funds</h3></div><div class="tbl"><table class="t n" style="min-width:560px"><thead><tr><th>Fund</th><th>Rating</th><th>Trend</th><th class="r">1 yr</th><th class="r">3 yr</th><th class="r">5 yr</th></tr></thead><tbody>${peers.map(p => `<tr style="${p.id === f.id ? 'box-shadow:inset 3px 0 0 var(--gold);background:var(--cream)' : ''}"><td><button class="fb" style="font-weight:${p.id === f.id ? 800 : 600}" data-f="${p.id}">${p.name}</button></td><td>${K.rate(p.rating)}</td><td>${K.spark(K.sparkFor(p), { w: 64, h: 22 })}</td><td class="r">${pc(p.r1)}</td><td class="r">${pc(p.r3)}</td><td class="r">${pc(p.r5)}</td></tr>`).join('')}</tbody></table></div></div>
  <p class="fine">Figures are illustrative. Read the scheme information document before investing.</p></div>
 <aside class="fd-s"><div class="panel pp inv"><div class="seg" id="ivm"><button data-m="sip" aria-pressed="true">Monthly SIP</button><button data-m="lump" aria-pressed="false">Lump sum</button></div><div class="amt"><span>₹</span><input id="ivA" inputmode="numeric" value="5,000" aria-label="Amount"></div><div class="chips" id="ivC">${[1000, 5000, 10000, 25000].map(a => `<button class="chip" data-a="${a}">+${a.toLocaleString('en-IN')}</button>`).join('')}</div><div class="ivr n" id="ivR"></div><button class="b b-go b-lg b-wide" data-now="${f.id}">Invest${ico('arrow', 'go')}</button><button class="b b-line b-wide" data-add="${f.id}" style="margin-top:10px">${inB ? 'In basket' : 'Add to basket'}</button><p class="fine" style="margin-top:12px;text-align:center">Minimum SIP ₹${f.minsip}. Cancel any time.</p></div>
 <div class="panel pp mgr"><small>Fund manager</small><div>${K.avatar(f.id + 2, { size: 44 })}<span><b>${f.mgr}</b><small>${f.age} years with ${f.amc}</small></span></div></div></aside></div>`; };
  A.wire_fund = id => { const f = K.fund(id); let m = 's';
    const ch = d => { const p = navPts(f, d); K.chart($('#cb'), { h: 290, series: [{ name: 'NAV', data: p.out, color: 'var(--teal)', fill: 'color-mix(in srgb,var(--teal) 10%,transparent)' }], x: i => p.lab[i], xticks: 5, fmt: v => '₹' + v.toFixed(2), yfmt: v => '₹' + Math.round(v), ymin: Math.min(...p.out) * .96, pl: 60 }); $('#cb')._drawn = false };
    ch(365); $('#rg').onclick = e => { const b = e.target.closest('button'); if (!b) return; $$('#rg button').forEach(x => x.setAttribute('aria-pressed', x === b)); ch(+b.dataset.d) };
    const run = () => { const a = +$('#ra').value, y = +$('#ry').value, r = f['r' + (y >= 5 ? 5 : y >= 3 ? 3 : 1)]; $('#raL').textContent = inr(a); $('#ryL').textContent = y + (y > 1 ? ' years ago' : ' year ago'); let i, v; if (m === 's') { i = a * 12 * y; v = K.sipFV(a, y, r) } else { i = a; v = a * Math.pow(1 + r / 100, y) }
      $('#ro').innerHTML = `<div><small>You would have put in</small><b>${inr(i)}</b></div><div><small>Worth today</small><b>${inr(v)}</b></div><div><small>Gain</small><b class="${v >= i ? 'up' : 'dn'}">${inr(v - i)}</b></div><div><small>Per year</small><b>${r.toFixed(1)}%</b></div>` };
    $('#ra').oninput = run; $('#ry').oninput = run; $$('#rm button').forEach(b => b.onclick = () => { m = b.dataset.m; $$('#rm button').forEach(x => x.setAttribute('aria-pressed', x === b)); run() }); K.fillAll($('#am')); run();
    let ivm = 'sip'; const iv = () => { const a = +($('#ivA').value.replace(/\D/g, '')) || 0, r = f.r3; const yrs = ivm === 'sip' ? 10 : 10, fv = ivm === 'sip' ? K.sipFV(a, yrs, r) : a * Math.pow(1 + r / 100, yrs); $('#ivR').innerHTML = `<span>In ${yrs} years, at the 3-year return of ${r.toFixed(1)}%</span><b>${L(fv)}</b>` };
    $('#ivm').onclick = e => { const b = e.target.closest('button'); if (!b) return; ivm = b.dataset.m; $$('#ivm button').forEach(x => x.setAttribute('aria-pressed', x === b)); iv() }; $('#ivA').oninput = e => { const n = +e.target.value.replace(/\D/g, ''); e.target.value = n ? n.toLocaleString('en-IN') : ''; iv() }; $('#ivC').onclick = e => { const c = e.target.closest('.chip'); if (!c) return; $('#ivA').value = ((+$('#ivA').value.replace(/\D/g, '') || 0) + +c.dataset.a).toLocaleString('en-IN'); iv() }; iv();
    A.fundIv = () => ({ t: ivm, amt: +($('#ivA').value.replace(/\D/g, '')) || 5000 }) };

  /* =============== SHELL =============== */
  K.app = {
    build() {
      $('#side .logo').outerHTML = K.brand('#/app/overview', true);
      $('#snav').innerHTML = SN.map(g => `<div class="sgrp"><h6>${g[0]}</h6>${g[1].map(i => `<a href="#/app/${i[0]}" data-s="${i[0]}">${ico(i[2])}<span>${i[1]}</span>${i[3] ? `<span class="tag">${i[3]}</span>` : ''}</a>`).join('')}</div>`).join('');
      $('#side .who').innerHTML = `${K.avatar(1, { size: 44 })}<div><b>Priya Subramanian</b><small>Your wealth manager</small></div>`;
      $('#sideBtn').innerHTML = ico('menu'); $('#find .fi').innerHTML = ico('search'); $('#cartBtn .ci').innerHTML = ico('bag'); $('#bellBtn .bi2').innerHTML = ico('bell');
      $('#bellM').innerHTML = `<h6>Notifications</h6><a class="nt" href="#/app/mf/transactions"><span class="ic">${ico('check')}</span><span><b>SIP of ₹10,000 processed</b><small>Arya Flexi Cap · 2 Oct</small></span></a><a class="nt" href="#/app/profile/nominee"><span class="ic" style="background:var(--gold-soft);color:var(--gold-2)">${ico('flag')}</span><span><b>Add a nominee</b><small>Takes two minutes</small></span></a>`;
      $('#meM').innerHTML = `<h6>Profile</h6><a href="#/app/profile/investors">${ico('users')}Family members</a><a href="#/app/profile/bank">${ico('bank')}Bank accounts and mandates</a><a href="#/app/profile/nominee">${ico('user')}Nominees</a><a href="#/app/profile/risk">${ico('target')}Risk profile</a><hr><a href="#/app/reports">${ico('doc')}Statements and reports</a><a href="#/app/kyc">${ico('shield')}KYC status</a><a href="#/app/help">${ico('chat')}Help</a><hr><a href="#/">${ico('logout')}Log out</a>`;
      $('#bnav').innerHTML = [['overview', 'Home', 'home'], ['mf/portfolio', 'Portfolio', 'pie'], ['mf/invest', 'Invest', 'chart'], ['calc', 'Tools', 'refresh']].map(i => `<a href="#/app/${i[0]}" data-s="${i[0]}">${ico(i[2])}<span>${i[1]}</span></a>`).join('') + `<button id="bMore">${ico('menu')}<span>More</span></button>`;
      $('#bMore').onclick = () => $('#side').classList.toggle('open'); $('#sideBtn').onclick = () => $('#side').classList.toggle('open');
      const menu = (b, m) => $(b).onclick = e => { e.stopPropagation(); $$('.menu').forEach(x => { if (x !== $(m)) x.classList.remove('show') }); $(m).classList.toggle('show') }; menu('#meBtn', '#meM'); menu('#bellBtn', '#bellM');
      document.addEventListener('click', e => { if (!e.target.closest('.menu')) $$('.menu').forEach(x => x.classList.remove('show')); if (!e.target.closest('#find')) $('#fres').classList.remove('show'); if (!e.target.closest('#side') && !e.target.closest('#sideBtn') && !e.target.closest('#bMore')) $('#side').classList.remove('open') });
      /* search with live results */
      const gq = $('#gq'), fres = $('#fres');
      gq.oninput = () => { const q = gq.value.trim().toLowerCase(); if (!q) { fres.classList.remove('show'); return } const r = F.filter(f => f.name.toLowerCase().includes(q) || f.cat.toLowerCase().includes(q)).slice(0, 6); fres.innerHTML = r.length ? r.map(f => `<button data-f="${f.id}"><span><b>${f.name}</b><small>${f.cat} · ${f.sub}</small></span><span class="n up">${f.r3.toFixed(1)}%</span></button>`).join('') + `<button data-all><b>See all results for “${K.esc(gq.value)}”</b></button>` : '<div class="none" style="padding:18px">No funds found</div>'; fres.classList.add('show') };
      gq.onkeydown = e => { if (e.key === 'Enter') { A.ex.q = gq.value; A.ex.c = 'All'; fres.classList.remove('show'); if (location.hash === '#/app/mf/explore') A.render(); else location.hash = '#/app/mf/explore' } };
      fres.onclick = e => { if (e.target.closest('[data-all]')) { A.ex.q = gq.value; A.ex.c = 'All'; fres.classList.remove('show'); if (location.hash === '#/app/mf/explore') A.render(); else location.hash = '#/app/mf/explore' } else if (e.target.closest('[data-f]')) { fres.classList.remove('show'); gq.value = '' } };
      document.addEventListener('keydown', e => { if (e.key === '/' && document.body.classList.contains('in') && !/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)) { e.preventDefault(); gq.focus() } });
      A.sync();
    },
    show(h) { const [p, q] = h.split('?'); if (q) { const c = new URLSearchParams(q).get('c'); if (c) A.ex.c = c } A.cur = p; A.render(); window.scrollTo(0, 0); K.observe($('#am')) }
  };
  A.sync = () => { $('#cnt').textContent = A.cart.size; $('#cnt').hidden = !A.cart.size };
  A.render = () => {
    const p = A.cur, m = $('#am'), isMF = p.startsWith('mf/') || p.startsWith('fund/');
    $('#tabsnav').hidden = !isMF; if (isMF) $('#tabsnav').innerHTML = MF.map(t => `<a href="#/app/mf/${t[0]}" class="${p === 'mf/' + t[0] || (t[0] === 'explore' && p.startsWith('fund/')) ? 'on' : ''}">${t[1]}</a>`).join('');
    const key = p.startsWith('fund/') || p.startsWith('mf/explore') ? 'mf/invest' : p === 'mf/transactions' ? 'mf/portfolio' : p.startsWith('profile') ? '' : p;
    $$('#snav a,#bnav a').forEach(a => a.classList.toggle('on', a.dataset.s === key));
    const v = p.startsWith('fund/') ? A.V.fund(+p.split('/')[1]) : p.startsWith('profile/') ? A.V.profile(p.split('/')[1]) : (A.V[p] || A.V.overview)();
    m.innerHTML = v; m.classList.remove('pgin'); void m.offsetWidth; m.classList.add('pgin');
    if (p === 'overview' || (!A.V[p] && !p.startsWith('fund/') && !p.startsWith('profile/'))) A.wire_overview(); else if (p === 'mf/portfolio') A.wire_portfolio(); else if (p === 'mf/explore') A.wire_explore(); else if (p.startsWith('fund/')) A.wire_fund(+p.split('/')[1]); else if (A['w_' + p.replace(/\//g, '_')]) A['w_' + p.replace(/\//g, '_')]();
    if (m.querySelector('#chub')) K.calcHub($('#chub'), 'sip');
    K.fillAll(m); K.observe(m); $('#side').classList.remove('open');
  };
})(window.K);
