/* Kosha Wealth — logged-in app: remaining screens + basket */
(function (K) {
  const { $, $$, ico, inr, L, pc, F, GOALS } = K, A = K.A, ah = A.ah;

  /* ---------- transactions ---------- */
  const TX = [['2 Oct 2026', 'Arya Flexi Cap Fund', 'SIP', 10000, 'Units allotted', 'refresh'], ['2 Oct 2026', 'Kaveri Mid Cap Fund', 'SIP', 5000, 'Units allotted', 'refresh'], ['18 Sep 2026', 'Bharat Liquid Fund', 'Lump sum', 50000, 'Units allotted', 'wallet'], ['5 Sep 2026', 'Meridian Tax Saver Fund', 'SIP', 5000, 'Units allotted', 'refresh'], ['28 Aug 2026', 'Sahyadri Short Duration Fund', 'Withdrawal', 20000, 'Paid to bank', 'download'], ['2 Aug 2026', 'Arya Flexi Cap Fund', 'SIP', 10000, 'Units allotted', 'refresh'], ['2 Aug 2026', 'Kaveri Mid Cap Fund', 'SIP', 5000, 'Units allotted', 'refresh']];
  let txf = 'All';
  A.V['mf/transactions'] = () => { const list = TX.filter(t => txf === 'All' || (txf === 'SIPs' ? t[2] === 'SIP' : txf === 'Lump sum' ? t[2] === 'Lump sum' : t[2] === 'Withdrawal')), groups = {}; list.forEach(t => (groups[t[0].split(' ').slice(1).join(' ')] ||= []).push(t));
    return `${ah('Transactions', '', `<div class="seg"><button aria-pressed="true">3 months</button><button aria-pressed="false">1 year</button><button aria-pressed="false">All</button></div><button class="b b-line b-sm" data-toast="Statement downloaded (demo)">${ico('download')}Download</button>`)}
 <div class="chips" id="txc">${['All', 'SIPs', 'Lump sum', 'Withdrawals'].map(c => `<button class="chip" data-c="${c}" aria-pressed="${c === txf}">${c}</button>`).join('')}</div>
 ${Object.entries(groups).map(([m, ts]) => `<section class="txg"><h4>${m}<span class="n">${inr(ts.reduce((s, t) => s + (t[2] === 'Withdrawal' ? -t[3] : t[3]), 0))} net</span></h4><div class="panel">${ts.map(t => `<div class="txr"><span class="ic ${t[2] === 'Withdrawal' ? 'out' : ''}">${ico(t[5])}</span><span class="nm"><b>${t[1]}</b><small>${t[0]} · ${t[2]}</small></span><span class="n am ${t[2] === 'Withdrawal' ? '' : ''}">${t[2] === 'Withdrawal' ? '−' : ''}${inr(t[3])}</span><span class="pill up">${t[4]}</span></div>`).join('')}</div></section>`).join('') || '<div class="none">Nothing here yet.</div>'}`; };
  A.w_mf_transactions = () => { $('#txc').onclick = e => { const c = e.target.closest('.chip'); if (c) { txf = c.dataset.c; A.render() } } };

  /* ---------- bonds ---------- */
  const RC = { AAA: '#14804F', 'AA−': '#0A8D99', 'A+': '#6B63D8', A: '#6B63D8', 'A−': '#E8A317', 'BBB+': '#D9573B' }; let bf = 0;
  A.V.bonds = () => { const B = K.BONDS.filter(b => [() => 1, () => b[3] > 10, () => b[7] < 24, () => ['AAA', 'AA−'].includes(b[1]), () => b[6] === 'Monthly', () => b[2] === 'Secured'][bf]());
    return `${ah('Bonds', 'Listed on NSE and BSE. Interest goes straight to your bank account.', `<div class="seg"><button aria-pressed="true">Explore</button><button aria-pressed="false" data-toast="Bond baskets (demo)">Baskets</button><button aria-pressed="false" data-toast="No bonds held yet (demo)">My bonds</button></div>`)}
 <div class="hi"><div><small>Best yield today</small><b class="n serif">11.40%</b></div><div><small>Typical maturity</small><b class="n serif">1–7 yrs</b></div><div><small>Minimum</small><b class="n serif">₹10,000</b></div></div>
 <div class="chips" id="bdc">${['All', 'Yield over 10%', 'Under 2 years', 'AAA and AA', 'Monthly interest', 'Secured only'].map((c, i) => `<button class="chip" data-c="${i}" aria-pressed="${i === bf}">${c}</button>`).join('')}</div>
 <div class="panel pp">${B.map(b => `<div class="bdr n"><span class="rt-b" style="background:${RC[b[1]]}">${b[1]}</span><div class="nm"><b>${b[0]}</b><small>${b[2]} · ${b[6]} interest · ${b[4]} left</small></div><div class="y"><b>${b[3].toFixed(2)}%</b><small>yield</small></div><button class="addb" data-toast="Bond order flow (demo)">Invest from ${inr(b[5])}</button></div>`).join('') || '<div class="none">No bonds match.</div>'}</div>
 <p class="fine">Offered through a SEBI-registered Online Bond Platform Provider partner. Bonds carry credit, interest-rate and liquidity risk. Issuer names are fictional.</p>`; };
  A.w_bonds = () => { $('#bdc').onclick = e => { const c = e.target.closest('.chip'); if (c) { bf = +c.dataset.c; A.render() } } };

  /* ---------- product landing pages ---------- */
  const prod = (o) => `<div class="prodh" style="--c:${o.c}"><div><span class="pill">${ico(o.ic)} ${o.tag}</span><h2 class="serif">${o.t}</h2><p>${o.d}</p><div class="acts"><button class="b b-ink b-lg" data-toast="${o.cta} (demo)">${o.cta}${ico('arrow', 'go')}</button><a class="b b-line b-lg" href="#/app/calc">Run the numbers</a></div></div><div class="pv">${o.vis}</div></div>
 <div class="pts">${o.pts.map((p, i) => `<div><span class="ic">${ico(p[2] || 'check')}</span><h3>${p[0]}</h3><p>${p[1]}</p></div>`).join('')}</div>`;
  A.V.fd = () => `${ah('Fixed deposits')}${prod({ ic: 'coin', c: 'var(--rose)', tag: 'Rated issuers', t: 'Fixed deposits from rated companies', d: 'Fixed interest paid monthly, quarterly or at maturity. Only issuers rated AA or higher.', cta: 'See current rates', vis: `<div class="mini"><small class="muted">3 year deposit</small><div class="big-rate n">8.5<small>%</small></div><div class="chips" style="justify-content:center;margin-top:14px"><span class="chip">1 yr · 7.6</span><span class="chip">2 yr · 8.0</span><span class="chip on">3 yr · 8.5</span><span class="chip">5 yr · 8.3</span></div></div>`, pts: [['Rated issuers', 'Nothing below AA.', 'shield'], ['Your payout schedule', 'Monthly, quarterly or cumulative.', 'calendar'], ['Booked online', 'No forms, no branch visits.', 'bolt']] })}`;
  A.V.nps = () => `${ah('National Pension System')}${prod({ ic: 'sunrise', c: 'var(--up)', tag: 'Retirement', t: 'Retire on your terms, and save tax on the way', d: 'Retirement savings with an extra ₹50,000 deduction under Section 80CCD(1B), on top of 80C.', cta: 'Open an NPS account', vis: `<div class="mini"><small class="muted">Extra tax saving room</small><div class="taxbar" style="margin:14px 0"><div style="flex:3;background:var(--teal)">80C · ₹1.5 L</div><div style="flex:1;background:var(--gold);color:#2A1C00">NPS</div></div><div style="display:flex;justify-content:space-between"><span class="muted sm">Saved at 30% slab</span><b class="serif n" style="font-size:1.6rem;color:var(--up)">₹15,600</b></div></div>`, pts: [['Low cost', 'Among the cheapest retirement products in India.', 'coin'], ['Your mix', 'Choose how much goes into equity and debt.', 'pie'], ['Extra tax saving', 'Beyond the ₹1.5 lakh 80C limit.', 'percent']] })}`;
  A.V.equity = () => `${ah('Stocks')}${prod({ ic: 'trend', c: 'var(--violet)', tag: 'Trading account', t: 'Stocks, with the reasoning shown', d: 'Open a trading and demat account, with research notes and stock SIPs.', cta: 'Open a trading account', vis: `<div class="mini"><div class="frow"><span class="lg" style="background:#232A73">A</span><span><b>Arya Industries</b><small>Stock SIP · ₹5,000 monthly</small></span><span class="sp">${K.spark(K.sparkFor(F[3]), { w: 70, h: 26 })}</span><span class="rt n">+12.4%<small>1 yr</small></span></div><div class="frow"><span class="lg" style="background:#0A6F78">N</span><span><b>Nilgiri Bank</b><small>Research note · Hold</small></span><span class="sp">${K.spark(K.sparkFor(F[7]), { w: 70, h: 26 })}</span><span class="rt n">+8.1%<small>1 yr</small></span></div></div>`, pts: [['Stock SIPs', 'Buy a fixed amount of chosen shares each month.', 'refresh'], ['Research notes', 'Reasoning for every idea, including when to exit.', 'doc'], ['Simple pricing', 'First-year account charges waived.', 'coin']] })}`;
  A.V.insurance = () => `${ah('Insurance')}${prod({ ic: 'shield', c: 'var(--gold-2)', tag: 'Term and health', t: 'So a crisis does not force you to sell investments', d: 'Term life and health cover, sized to your income and loans, then left alone.', cta: 'Get a quote', vis: `<div class="mini" style="text-align:center"><span class="ic" style="width:64px;height:64px;border-radius:20px;background:var(--ink);color:var(--bg);display:grid;place-items:center;margin:0 auto 14px">${ico('shield')}</span><small class="muted">Suggested term cover</small><div class="serif n" style="font-size:3rem;color:var(--ink);line-height:1.1">₹1 Crore</div><span class="pill">from ₹760 a month</span></div>`, pts: [['Term life', 'Large cover at a low premium.', 'heart'], ['Health', 'Cashless treatment at network hospitals.', 'plus'], ['Claims help', 'We stay with you through the claim.', 'users']] })}`;
  A.V.sif = () => `${ah('Specialised Investment Funds', 'A newer SEBI category between mutual funds and PMS. Long-short strategies, minimum ₹10 lakh.')}<div class="sif" style="margin-bottom:8px">${[['Mutual fund', 'From ₹500', 'Long-only, daily NAV.', 0], ['SIF', 'From ₹10 lakh', 'Can go long and short, within SEBI limits.', 1], ['PMS', 'From ₹50 lakh', 'A portfolio built just for you.', 0]].map((s, i) => `<div class="${s[3] ? 'hl' : ''}"><span class="no">0${i + 1}</span><h3>${s[0]}</h3><b class="n">${s[1]}</b><p>${s[2]}</p>${s[3] ? '<span class="pill gold">You are here</span>' : ''}</div>`).join('')}</div>
 <div class="panel pp"><div class="tbl"><table class="t n" style="min-width:640px"><thead><tr><th>Fund</th><th>Strategy</th><th>Risk</th><th class="r">NAV</th><th></th></tr></thead><tbody>${[['Arya Equity Long-Short', 'Equity long-short', 'Very high', 10.42], ['Kaveri Hybrid Long-Short', 'Hybrid long-short', 'Moderate', 10.18], ['Meridian Ex-Top 100', 'Equity, outside top 100', 'Very high', 9.94], ['Vistara Debt Long-Short', 'Debt long-short', 'Low', 10.07]].map(s => `<tr><td><b style="color:var(--ink)">${s[0]}</b></td><td>${s[1]}</td><td><span class="pill ${s[2] === 'Low' ? 'up' : s[2] === 'Moderate' ? 'gold' : 'rose'}">${s[2]}</span></td><td class="r">₹${s[3]}</td><td class="r"><button class="addb" data-toast="SIF order flow (demo)">Invest</button></td></tr>`).join('')}</tbody></table></div></div>`;

  /* ---------- net worth ---------- */
  const NW = [['Bank accounts', 'bank', 420000, '#0A8D99'], ['Mutual funds held elsewhere', 'chart', 680000, '#6B63D8'], ['Shares and demat', 'trend', 310000, '#D9573B'], ['NPS', 'sunrise', 240000, '#14804F'], ['EPF and PPF', 'coin', 860000, '#E8A317']], linked = new Set();
  A.V.networth = () => { const tot = [...linked].reduce((s, i) => s + NW[i][2], 0), segs = [['Kosha investments', 100, '#10143A'], ...[...linked].map(i => [NW[i][0], NW[i][2] / (CURV() / 100), NW[i][3]])]; return `${ah('Net worth', 'Everything you own, on one page. Powered by the RBI Account Aggregator network.')}
 <div class="nwg"><div class="panel pp nwh"><small class="muted">Your net worth</small><div class="serif n big" id="nwT">${inr(CURV() + tot)}</div><p class="sm muted">${linked.size ? `${linked.size} account${linked.size > 1 ? 's' : ''} linked, plus your Kosha investments.` : 'Link accounts to add them here. You choose exactly what to share.'}</p><div class="alloc" style="margin-top:26px"><div class="ringv">${K.donut(segs, { size: 170, thick: 24 })}<div><b class="n serif" style="font-size:1.4rem;color:var(--ink)">${K.L(CURV() + tot)}</b></div></div><div class="alg">${segs.map(s => `<div><span><i style="background:${s[2]}"></i>${s[0]}</span></div>`).join('')}</div></div></div>
 <div class="nwl">${NW.map((n, i) => `<div class="nwi ${linked.has(i) ? 'on' : ''}"><span class="ic" style="--c:${n[3]}">${ico(n[1])}</span><span><b>${n[0]}</b><small>${linked.has(i) ? inr(n[2]) + ' · linked' : 'Not linked'}</small></span><button class="b ${linked.has(i) ? 'b-line' : 'b-go'} b-sm" data-nw="${i}">${linked.has(i) ? 'Unlink' : 'Link'}</button></div>`).join('')}<p class="fine">Demo values. In production, consent is requested through your bank’s Account Aggregator app and can be withdrawn at any time.</p></div></div>`; };
  const CURV = () => A.H.reduce((s, h) => s + h[2], 0);
  A.w_networth = () => { $('.nwl').onclick = e => { const b = e.target.closest('[data-nw]'); if (!b) return; const i = +b.dataset.nw; linked.has(i) ? linked.delete(i) : linked.add(i); K.toast(linked.has(i) ? NW[i][0] + ' linked (demo consent)' : 'Consent withdrawn'); A.render() } };

  /* ---------- profile ---------- */
  const PROF = [['investors', 'Family members'], ['bank', 'Bank and mandates'], ['nominee', 'Nominees'], ['risk', 'Risk profile']];
  A.V.profile = s => { let b = '';
    if (s === 'bank') b = `<div class="panel pp"><div class="ph2"><h3>Bank accounts</h3><button class="lnk" data-toast="Add a bank by paying ₹1 over UPI (demo)">Add a bank ${ico('plus')}</button></div><div class="row3"><span class="ic">${ico('bank')}</span><div class="nm"><b>HDFC Bank, savings, ending 6549</b><small>Primary account for investments and withdrawals</small></div><span class="pill up">Verified</span></div></div><div class="panel pp"><div class="ph2"><h3>Autopay mandates</h3><button class="lnk" data-toast="UPI Autopay or e-NACH setup (demo)">Set up a mandate ${ico('plus')}</button></div><p class="muted">None yet. A mandate lets your bank pay SIPs automatically. We can never take more than the SIP amount, and you can cancel it any time.</p></div>`;
    else if (s === 'nominee') b = `<div class="panel pp"><h3>Add a nominee</h3><p class="muted sm" style="margin:6px 0 22px">You can add up to ten and split your investments between them.</p><div class="f2"><div class="fld"><label>Full name</label><input></div><div class="fld"><label>Relationship</label><select><option>Spouse</option><option>Child</option><option>Parent</option><option>Sibling</option></select></div><div class="fld"><label>Date of birth</label><input type="date"></div><div class="fld"><label>Share</label><input value="100%"></div></div><button class="b b-go" style="margin-top:22px" data-toast="Nominee saved (demo)">Save nominee</button></div>`;
    else if (s === 'risk') b = `<div class="panel pp"><h3>Risk profile</h3><p class="muted sm" style="margin:6px 0 24px">Two of six short questions. There are no wrong answers.</p>${[['When will you need most of this money?', ['Within 3 years', 'In 3 to 7 years', 'After 7 years']], ['Your investments fall 20% in a month. What do you do?', ['Sell to stop the loss', 'Wait it out', 'Invest more while prices are low']]].map((q, i) => `<fieldset class="q"><legend>${i + 1}. ${q[0]}</legend><div class="opts">${q[1].map((o, k) => `<label class="opt"><input type="radio" name="q${i}" ${k === 1 ? 'checked' : ''}><span>${o}</span></label>`).join('')}</div></fieldset>`).join('')}<button class="b b-go" data-toast="Your profile: moderately aggressive (demo)">See my profile</button></div>`;
    else b = `<div class="panel pp"><div class="ph2"><h3>People on this account</h3><button class="lnk" data-toast="Add a family member (demo)">Add a family member ${ico('plus')}</button></div><div class="row3"><span>${K.avatar(0, { size: 46 })}</span><div class="nm"><b>Ravi Kumar</b><small>Primary holder</small></div><span class="pill up">KYC verified</span></div><p class="fine" style="margin-top:16px">Add your spouse, parents or children to manage the family’s investments from one login. Joint holdings are supported.</p></div>`;
    return `${ah('Profile')}<div class="chips">${PROF.map(t => `<a class="chip" href="#/app/profile/${t[0]}" aria-pressed="${t[0] === s}">${t[1]}</a>`).join('')}</div>${b}`; };

  /* ---------- kyc / reports / help ---------- */
  A.V.kyc = () => `${ah('KYC', 'Completed on 6 October 2026 through DigiLocker.', `<span class="pill up">${ico('shield')} Fully verified</span>`)}<div class="kycs">${[['PAN and Aadhaar fetched from DigiLocker', '6 Oct, 10:12 am', 'doc'], ['Signature uploaded', '6 Oct, 10:15 am', 'user'], ['Selfie verified', '6 Oct, 10:16 am', 'eye'], ['Bank account confirmed with ₹1 over UPI', '6 Oct, 10:21 am', 'bank']].map(s => `<div><span class="ck">${ico('check')}</span><span class="nm"><b>${s[0]}</b><small>${s[1]}</small></span><span class="pill up">Done</span></div>`).join('')}</div><p class="fine">Could not receive the Aadhaar OTP? The offline route uses a signed account opening form.</p>`;
  A.V.reports = () => `${ah('Statements and reports')}<div class="rpt">${[['Portfolio statement', 'pie'], ['Capital gains, for tax filing', 'percent'], ['All transactions', 'receipt'], ['Consolidated account statement', 'layers'], ['SIP summary', 'refresh'], ['Tax-saving (ELSS) proof', 'leaf']].map(r => `<button data-toast="${r[0]} downloaded (demo)"><span class="ic">${ico(r[1])}</span><b>${r[0]}</b><small>PDF or Excel, any date range</small><span class="dl2">${ico('download')}</span></button>`).join('')}</div>`;
  A.V.help = () => `${ah('Help')}<div class="hp"><div><div class="hq"><span>${ico('search')}</span><input id="hq" placeholder="Search questions" aria-label="Search help"></div><div id="hl">${K.faqHTML()}</div></div><div class="hc"><div class="panel pp"><span class="ic">${ico('phone')}</span><h3>Call Priya</h3><p class="muted sm">Your wealth manager, usually free within the hour.</p><button class="b b-go b-sm" data-toast="Call request sent (demo)">Request a call</button></div><div class="panel pp"><span class="ic">${ico('chat')}</span><h3>Chat with support</h3><p class="muted sm">For orders, KYC and bank issues. 9am to 7pm.</p><button class="b b-line b-sm" data-toast="Chat opens (demo)">Start a chat</button></div></div></div>`;
  A.w_help = () => { const all = $$('#hl details'); $('#hq').oninput = e => { const q = e.target.value.toLowerCase(); all.forEach(d => d.style.display = d.textContent.toLowerCase().includes(q) ? '' : 'none') } };
  A.V.calc = () => `${ah('Calculators')}<div id="chub"></div>`;

  /* ---------- basket ---------- */
  const cart = A.cart, put = (id, o) => cart.set(id, Object.assign({ t: 'sip', k: 'Regular', amt: 5000 }, o || {}));
  const tog = id => { if (cart.has(id)) { cart.delete(id); K.toast('Removed from basket') } else { put(id); K.toast('Added to basket') } A.sync(); if (document.body.classList.contains('in')) A.render() };
  document.addEventListener('click', e => {
    const f = e.target.closest('[data-f]'); if (f) { location.hash = '#/app/fund/' + f.dataset.f; return }
    const a = e.target.closest('[data-add]'); if (a) { tog(+a.dataset.add); return }
    const n = e.target.closest('[data-now]'); if (n) { const id = +n.dataset.now, o = A.fundIv && location.hash.startsWith('#/app/fund/') ? A.fundIv() : {}; put(id, o); A.sync(); openD() }
  });
  function basket() { const b = $('#bb'), f = $('#bf'); $('#bsub').textContent = cart.size ? cart.size + ' fund' + (cart.size > 1 ? 's' : '') : '';
    if (!cart.size) { b.innerHTML = `<div class="none"><span class="ic0">${ico('bag')}</span><h3 class="serif" style="font-size:1.5rem">Nothing here yet</h3><p>Add funds and invest in all of them in one go.</p><a class="b b-go" style="margin-top:18px" href="#/app/mf/explore" data-cb>Browse funds</a></div>`; f.innerHTML = ''; return }
    b.innerHTML = [...cart].map(([id, o]) => { const x = F.find(y => y.id === id); return `<div class="bi" data-i="${id}"><div style="display:flex;justify-content:space-between;gap:12px"><b style="color:var(--ink)">${x.name}</b><button class="x" style="font-size:1.3rem" data-rm aria-label="Remove">×</button></div>
  <div class="seg"><button data-t="sip" aria-pressed="${o.t === 'sip'}">Monthly SIP</button><button data-t="lump" aria-pressed="${o.t === 'lump'}">Lump sum</button></div>
  ${o.t === 'sip' ? `<div class="fld"><label>Type of SIP</label><div class="seg">${['Regular', 'Flexi', 'Step-up'].map(k => `<button data-k="${k}" aria-pressed="${o.k === k}">${k}</button>`).join('')}</div></div>` : ''}
  <div class="f2"><div class="fld"><label>${o.t === 'sip' ? 'Each month' : 'Amount'}</label><input data-amt inputmode="numeric" value="${o.amt}"></div>${o.t === 'sip' ? `<div class="fld"><label>Debit on</label><select>${[1, 5, 10, 15, 20, 25].map(d => `<option ${d === 5 ? 'selected' : ''}>${d}th</option>`).join('')}</select></div>` : `<div class="fld"><label>Folio</label><select><option>New folio</option></select></div>`}</div>
  ${o.t === 'sip' ? `<div class="f2"><div class="fld"><label>Until</label><select><option>I stop it</option><option>12 months</option><option>3 years</option><option>5 years</option><option>10 years</option></select></div><div class="fld"><label>For goal</label><select>${GOALS.map(g => `<option>${g.name}</option>`).join('')}</select></div></div>` : `<div class="fld"><label>For goal</label><select>${GOALS.map(g => `<option>${g.name}</option>`).join('')}</select></div>`}</div>` }).join('');
    const tot = [...cart.values()].reduce((s, o) => s + (+o.amt || 0), 0);
    f.innerHTML = `<div style="display:flex;justify-content:space-between;align-items:baseline;margin-bottom:14px" class="n"><span class="muted">Total</span><b id="btot" style="color:var(--ink);font-size:1.5rem;font-family:var(--serif);font-weight:400">${inr(tot)}</b></div><button class="b b-go b-lg b-wide" id="go">Review and confirm${ico('arrow', 'go')}</button><p class="fine" style="margin-top:10px">Money returns to HDFC Bank, ending 6549, when you withdraw.</p>`; $('#go').onclick = confirmB }
  function confirmB() { const sip = [...cart.values()].some(o => o.t === 'sip');
    $('#bb').innerHTML = sip ? `<div class="none" style="text-align:left;padding:8px 0"><span class="ic0">${ico('shield')}</span><h3 class="serif" style="font-size:1.6rem">One more step: an autopay mandate</h3><p style="margin-top:10px">It lets your bank pay SIP instalments on the date you picked. We can never take more than your SIP amount, and you can cancel it from your profile at any time.</p><p style="margin-top:10px">It takes about two minutes with UPI Autopay, or a little longer with net banking.</p></div>`
      : `<div><h3 class="serif" style="font-size:1.5rem">Order summary</h3><div class="dl n" style="margin-top:10px">${[...cart].map(([id, o]) => `<div><small>${F.find(x => x.id === id).name}</small><b>${inr(o.amt)}</b></div>`).join('')}</div></div><div class="fld"><label>Pay with</label><div class="seg"><button aria-pressed="true">UPI</button><button aria-pressed="false">Net banking</button></div></div><p class="fine">Units are bought at the NAV of the day your money reaches the fund house.</p>`;
    $('#bf').innerHTML = (sip ? `<button class="b b-go b-lg b-wide" data-toast="UPI Autopay setup opens (demo)">Set up autopay</button>` : `<button class="b b-go b-lg b-wide" data-toast="Payment page opens (demo)">Pay now</button>`) + `<button class="b b-line b-wide" style="margin-top:10px" id="bk">Back to basket</button>`; $('#bk').onclick = basket }
  $('#bb').addEventListener('click', e => { if (e.target.closest('[data-cb]')) { K.closeAll(); return } const it = e.target.closest('[data-i]'); if (!it) return; const id = +it.dataset.i, o = cart.get(id);
    if (e.target.closest('[data-rm]')) { cart.delete(id); A.sync(); basket(); if (document.body.classList.contains('in')) A.render(); return } if (e.target.dataset.t) { o.t = e.target.dataset.t; basket() } if (e.target.dataset.k) { o.k = e.target.dataset.k; basket() } });
  $('#bb').addEventListener('input', e => { const it = e.target.closest('[data-i]'); if (it && e.target.hasAttribute('data-amt')) { cart.get(+it.dataset.i).amt = +e.target.value || 0; $('#btot').textContent = inr([...cart.values()].reduce((s, o) => s + (+o.amt || 0), 0)) } });
  function openD() { basket(); $('#drawer').classList.add('show'); $('#drawer').setAttribute('aria-hidden', 'false'); $('#scrim').classList.add('show') }
  $('#cartBtn').onclick = openD; $('#dx').onclick = () => K.closeAll();
})(window.K);
