/* Kosha Wealth — calculator hub (six calculators, one engine) */
(function (K) {
  const { $, $$, ico, inr, L } = K;
  const yrs = v => v + (v > 1 ? ' yrs' : ' yr'), pct = v => v + '%', yr0 = new Date().getFullYear();
  const stackOut = (invested, growth, o = {}) => ({ chart: { stack: true, series: [{ name: 'You invest', data: invested, color: '#7FD8E0', fill: 'rgba(127,216,224,.28)' }, { name: 'Growth', data: growth, color: '#E8A317', fill: 'rgba(232,163,23,.42)' }], x: i => yr0 + i, tipx: i => 'Year ' + i, total: 'Total value', xticks: 5, ...o }, legend: [['#7FD8E0', 'You invest'], ['#E8A317', 'Growth']] });

  K.CALCS = [
    { k: 'sip', n: 'SIP', ic: 'refresh', d: 'What a monthly investment grows to.', how: 'Each monthly instalment compounds from the day it is invested, using the formula FV = P × [((1+i)ⁿ − 1) ÷ i] × (1+i), where i is the monthly rate and n the number of months.',
      in: [{ id: 'a', l: 'Monthly investment', min: 500, max: 200000, step: 500, v: 10000, f: inr }, { id: 'y', l: 'Time period', min: 1, max: 40, v: 15, f: yrs }, { id: 'r', l: 'Expected return, per year', min: 4, max: 20, step: .5, v: 12, f: pct }],
      run: v => { const val = K.sipFV(v.a, v.y, v.r), inv = v.a * 12 * v.y, I = [], G = []; for (let k = 0; k <= v.y; k++) { const f = K.sipFV(v.a, k, v.r), i = v.a * 12 * k; I.push(i); G.push(Math.max(0, f - i)) } return { lab: `After ${yrs(v.y)}, you could have`, val: L(val), stats: [['You invest', L(inv)], ['Growth', L(val - inv)], ['Multiple', (val / inv).toFixed(1) + '×']], ...stackOut(I, G) } } },
    { k: 'lump', n: 'Lump sum', ic: 'wallet', d: 'One cheque, many years of compounding.', how: 'A single investment compounds yearly: FV = P × (1 + r)ⁿ. Time does most of the work, which is why the number grows faster in the later years than the early ones.',
      in: [{ id: 'a', l: 'Amount invested', min: 10000, max: 10000000, step: 10000, v: 500000, f: L }, { id: 'y', l: 'Time period', min: 1, max: 40, v: 15, f: yrs }, { id: 'r', l: 'Expected return, per year', min: 4, max: 20, step: .5, v: 12, f: pct }],
      run: v => { const val = v.a * Math.pow(1 + v.r / 100, v.y), I = [], G = []; for (let k = 0; k <= v.y; k++) { I.push(v.a); G.push(v.a * Math.pow(1 + v.r / 100, k) - v.a) } return { lab: `After ${yrs(v.y)}, it could be worth`, val: L(val), stats: [['You invest', L(v.a)], ['Growth', L(val - v.a)], ['Multiple', (val / v.a).toFixed(1) + '×']], ...stackOut(I, G) } } },
    { k: 'stepup', n: 'Step-up SIP', ic: 'trend', d: 'Raise your SIP a little every year.', how: 'Your instalment rises by the step-up percentage at the start of each year. Because your salary usually grows too, this is the single easiest way to reach a bigger goal without feeling it.',
      in: [{ id: 'a', l: 'Starting monthly SIP', min: 500, max: 200000, step: 500, v: 10000, f: inr }, { id: 's', l: 'Increase every year', min: 0, max: 25, step: 1, v: 10, f: pct }, { id: 'y', l: 'Time period', min: 1, max: 40, v: 15, f: yrs }, { id: 'r', l: 'Expected return, per year', min: 4, max: 20, step: .5, v: 12, f: pct }],
      run: v => { const i = v.r / 1200; let bal = 0, inv = 0, sip = v.a; const I = [0], G = [0]; for (let m = 1; m <= v.y * 12; m++) { bal = (bal + sip) * (1 + i); inv += sip; if (m % 12 === 0) { I.push(inv); G.push(Math.max(0, bal - inv)); sip *= 1 + v.s / 100 } } const flat = K.sipFV(v.a, v.y, v.r);
        return { lab: `With a ${v.s}% yearly step-up, after ${yrs(v.y)}`, val: L(bal), stats: [['You invest', L(inv)], ['Growth', L(bal - inv)], ['Beats a flat SIP by', L(bal - flat)]], ...stackOut(I, G) } } },
    { k: 'swp', n: 'SWP', ic: 'download', d: 'Monthly income from your savings.', how: 'Each month the fund earns a return and you withdraw a fixed amount. If the return is higher than the withdrawal rate, the pot lasts a long time. If not, it runs out, and the chart shows exactly when.',
      in: [{ id: 'c', l: 'Corpus to start with', min: 5e5, max: 5e7, step: 1e5, v: 5e6, f: L }, { id: 'w', l: 'Monthly withdrawal', min: 5000, max: 500000, step: 1000, v: 40000, f: inr }, { id: 'r', l: 'Expected return, per year', min: 4, max: 16, step: .5, v: 9, f: pct }, { id: 'y', l: 'Show for', min: 5, max: 40, v: 25, f: yrs }],
      run: v => { const i = v.r / 1200; let bal = v.c, lasted = null; const B = [v.c]; for (let m = 1; m <= v.y * 12; m++) { bal = bal * (1 + i) - v.w; if (bal <= 0 && lasted === null) { lasted = m; bal = 0 } if (m % 12 === 0) B.push(Math.max(0, bal)) } const done = lasted !== null, ly = lasted ? Math.floor(lasted / 12) + ' yrs ' + (lasted % 12) + ' mo' : '';
        return { lab: done ? 'Your money lasts' : `After ${yrs(v.y)}, you would still have`, val: done ? ly : L(bal), stats: [['Total withdrawn', L(v.w * (lasted || v.y * 12))], ['Start corpus', L(v.c)], ['Withdrawal rate', (v.w * 12 / v.c * 100).toFixed(1) + '%']], chart: { series: [{ name: 'Balance', data: B, color: done ? '#F08072' : '#7FD8E0', fill: done ? 'rgba(240,128,114,.2)' : 'rgba(127,216,224,.22)' }], x: i => yr0 + i, tipx: i => 'Year ' + i, xticks: 5, ymin: 0 }, legend: [[done ? '#F08072' : '#7FD8E0', 'Remaining balance']], warn: done ? 'At this rate the money runs out. Lower the withdrawal or raise the starting corpus.' : '' } } },
    { k: 'retire', n: 'Retirement', ic: 'sunrise', d: 'The corpus you need, and the SIP to build it.', how: 'We inflate today’s monthly spend to your retirement date, then work out the pot needed to fund it, rising with inflation, until age 85, assuming it earns 8% after you retire. The SIP is what builds that pot by then.',
      in: [{ id: 'age', l: 'Your age today', min: 20, max: 55, v: 30, f: v => v + ' yrs' }, { id: 'ret', l: 'Retire at', min: 45, max: 70, v: 60, f: v => v + ' yrs' }, { id: 'ex', l: 'Monthly spend today', min: 15000, max: 400000, step: 5000, v: 60000, f: inr }, { id: 'inf', l: 'Inflation', min: 3, max: 10, step: .5, v: 6, f: pct }, { id: 'r', l: 'Return while saving', min: 6, max: 16, step: .5, v: 11, f: pct }],
      run: v => { const n = Math.max(1, v.ret - v.age), E = v.ex * 12 * Math.pow(1 + v.inf / 100, n), N = Math.max(1, 85 - v.ret); let corpus = 0; for (let t = 0; t < N; t++) corpus += E * Math.pow(1 + v.inf / 100, t) / Math.pow(1.08, t); const s = K.need(corpus, n, v.r), I = [], G = []; for (let k = 0; k <= n; k++) { const f = K.sipFV(s, k, v.r), i = s * 12 * k; I.push(i); G.push(Math.max(0, f - i)) }
        return { lab: `To retire at ${v.ret}, you will need`, val: L(corpus), stats: [['Monthly SIP', inr(s)], ['Spend at retirement', inr(E / 12) + ' /mo'], ['Years to save', n + ' yrs']], ...stackOut(I, G), note: `Assumes you live to 85. Starting a year later would raise the SIP by about ${inr(K.need(corpus, n - 1, v.r) - s)} a month.` } } },
    { k: 'tax', n: 'Tax saving', ic: 'percent', d: 'What an 80C investment actually saves you.', how: 'Under the old tax regime, up to ₹1.5 lakh a year invested in ELSS, PPF, EPF or similar is deducted from your taxable income. The saving is that amount times your slab, plus 4% cess. It does not apply under the new regime.',
      in: [{ id: 'a', l: 'Invested in 80C this year', min: 10000, max: 300000, step: 5000, v: 150000, f: inr }, { id: 's', l: 'Your tax slab', type: 'chips', opts: [5, 10, 20, 30], v: 30 }, { id: 'y', l: 'Invest every year for', min: 3, max: 30, v: 10, f: yrs }, { id: 'r', l: 'Expected ELSS return', min: 6, max: 16, step: .5, v: 12, f: pct }],
      run: v => { const used = Math.min(v.a, 150000), save = used * v.s / 100 * 1.04, I = [], G = []; let bal = 0; for (let k = 0; k <= v.y; k++) { I.push(v.a * k); if (k) bal = (bal + v.a) * (1 + v.r / 100); G.push(Math.max(0, bal - v.a * k)) }
        return { lab: 'Tax you save this year', val: inr(save), stats: [['Counts under 80C', inr(used)], ['Real cost of investing', inr(v.a - save)], [`Saved over ${yrs(v.y)}`, L(save * v.y)]], ...stackOut(I, G), note: v.a > 150000 ? 'Only ₹1.5 lakh counts. The extra grows in the same fund but earns no extra tax benefit.' : '' } } }
  ];

  K.calcHub = (el, start, opt = {}) => {
    let cur = K.CALCS.find(c => c.k === start) || K.CALCS[0], vals = {};
    el.innerHTML = `<div class="ch"><div class="ch-l" role="tablist" aria-label="Calculators">${K.CALCS.map(c => `<button role="tab" data-k="${c.k}"><span class="ic">${ico(c.ic)}</span><span><b>${c.n}</b><small>${c.d}</small></span></button>`).join('')}</div><div class="ch-m"><div class="ch-in"></div><div class="ch-out dark"></div></div></div>`;
    const inEl = $('.ch-in', el), outEl = $('.ch-out', el);
    const run = () => { const r = cur.run(vals); outEl.innerHTML = `<div class="lab">${r.lab}</div><div class="val n">${r.val}</div><div class="cchart"></div><div class="legend" style="margin-top:8px">${r.legend.map(l => `<span><i style="background:${l[0]}"></i>${l[1]}</span>`).join('')}</div><div class="tm-chips n">${r.stats.map(s => `<div>${s[0]}<b>${s[1]}</b></div>`).join('')}</div>${r.note || r.warn ? `<div class="tm-late">${ico(r.warn ? 'info' : 'sparkle')}<span>${r.warn || r.note}</span></div>` : ''}`; K.chart($('.cchart', outEl), { h: 230, fmt: K.L, yfmt: K.short, ...r.chart }) };
    const paint = () => {
      $$('.ch-l button', el).forEach(b => b.setAttribute('aria-selected', b.dataset.k === cur.k)); vals = {}; cur.in.forEach(i => vals[i.id] = i.v);
      inEl.innerHTML = `<h3 class="serif" style="font-size:1.9rem;margin-bottom:6px">${cur.n} calculator</h3><p class="muted" style="margin-bottom:28px">${cur.d}</p>${cur.in.map(i => i.type === 'chips' ? `<div class="sl"><div class="top"><label>${i.l}</label></div><div class="chips" data-chip="${i.id}">${i.opts.map(o => `<button class="chip" data-v="${o}" aria-pressed="${o === i.v}">${o}%</button>`).join('')}</div></div>` : `<div class="sl"><div class="top"><label for="cc_${i.id}">${i.l}</label><span class="val n" id="cv_${i.id}">${i.f(i.v)}</span></div><input type="range" id="cc_${i.id}" min="${i.min}" max="${i.max}" step="${i.step || 1}" value="${i.v}"></div>`).join('')}<details class="hw"><summary>${ico('info')} How this is calculated</summary><p>${cur.how}</p></details><p class="fine" style="margin-top:14px">Mutual fund returns depend on markets and are not guaranteed. Use this to understand the effect of time, not to predict an outcome.</p>`;
      cur.in.forEach(i => { if (i.type === 'chips') return; const r = $('#cc_' + i.id, inEl); r.oninput = () => { vals[i.id] = +r.value; $('#cv_' + i.id, inEl).textContent = i.f(+r.value); run() } });
      $$('[data-chip]', inEl).forEach(g => g.onclick = e => { const c = e.target.closest('.chip'); if (!c) return; vals[g.dataset.chip] = +c.dataset.v; $$('.chip', g).forEach(x => x.setAttribute('aria-pressed', x === c)); run() });
      K.fillAll(inEl); run();
    };
    $('.ch-l', el).onclick = e => { const b = e.target.closest('button'); if (!b) return; cur = K.CALCS.find(c => c.k === b.dataset.k); paint(); if (opt.hash) history.replaceState(null, '', '#/calculators/' + cur.k) };
    paint();
  };
})(window.K);
