/* Kosha Wealth — fictional demo data. Every name, NAV, return and review here is a placeholder. */
(function (K) {
  K.GOALS = [
    { id: 'edu', name: "Child's education", short: 'Education', icon: 'cap', color: '#0A6F78', cost: 25, yrs: 12, infl: 8, desc: 'College fees in India climb faster than everyday prices. A ring-fenced portfolio keeps this money from quietly turning into something else.', mix: [55, 25, 10, 10], adv: ['Fees inflation of 8% built in, not the 6% in most calculators', 'A glide path that moves to safer funds 3 years before the first fee', 'Separate folios so the money cannot be dipped into'] },
    { id: 'ret', name: 'Retirement', short: 'Retirement', icon: 'sunrise', color: '#E8A317', cost: 200, yrs: 25, infl: 6, desc: 'Enough to replace your salary for 25 years after you stop, built mostly in equity while time is on your side.', mix: [45, 30, 15, 10], adv: ['A target based on your actual expenses, not a round number', 'Yearly step-ups so the SIP grows with your salary', 'A withdrawal plan drawn up before you retire, not after'] },
    { id: 'home', name: 'A home of your own', short: 'Home', icon: 'home', color: '#6B63D8', cost: 20, yrs: 6, infl: 7, desc: 'The down payment, so the loan stays small. We shift money to safer funds as the purchase date gets closer.', mix: [30, 20, 35, 15], adv: ['Down-payment target worked back from the property price', 'Money moves to debt funds in the last 24 months', 'Tax-efficient exit planning so you do not sell at the wrong time'] },
    { id: 'emg', name: 'Emergency money', short: 'Emergency', icon: 'shield', color: '#14804F', cost: 3, yrs: 1, infl: 6, desc: 'Six months of expenses in liquid funds you can withdraw the same day, so a bad month never touches your long-term plans.', mix: [0, 0, 90, 10], adv: ['Sized to six months of your real expenses', 'Only liquid and overnight funds, nothing with surprises', 'Instant redemption up to a limit with select funds'] },
    { id: 'trip', name: 'A family holiday', short: 'Holiday', icon: 'plane', color: '#D9573B', cost: 4, yrs: 2, infl: 6, desc: 'Save for the trip well ahead, so there is no credit card bill waiting when you get back.', mix: [10, 10, 70, 10], adv: ['Short-term debt funds, not equity, for a two-year goal', 'A monthly amount that fits quietly inside your budget', 'Redeem on the day you book, money in your bank next day'] },
    { id: 'wealth', name: 'Long-term wealth', short: 'Wealth', icon: 'trend', color: '#232A73', cost: 100, yrs: 15, infl: 6, desc: 'No fixed date, just steady growth. Spread across company sizes and investment styles, reviewed every quarter.', mix: [50, 30, 10, 10], adv: ['A core and satellite structure that is easy to understand', 'Rebalanced once a year, never on a market headline', 'Tax-aware sells so you keep more of what you earn'] }
  ];
  K.MIXC = [['Large companies', '#10143A'], ['Mid and small', '#0A6F78'], ['Debt', '#8C93C4'], ['Gold', '#E8A317']];

  /* ---------- fund universe (seeded so numbers stay stable) ---------- */
  const AMCS = ['Arya', 'Bharat', 'Kaveri', 'Meridian', 'Sahyadri', 'Vistara'];
  const CATS = ['Equity', 'Debt', 'Hybrid', 'ELSS', 'Index', 'Gold', 'Liquid'];
  const SUB = { Equity: ['Flexi Cap', 'Large Cap', 'Mid Cap', 'Small Cap', 'Large and Mid Cap'], Debt: ['Corporate Bond', 'Short Duration', 'Banking and PSU'], Hybrid: ['Balanced Advantage', 'Aggressive Hybrid'], ELSS: ['Tax Saver'], Index: ['Nifty 50 Index', 'Nifty Next 50 Index'], Gold: ['Gold'], Liquid: ['Liquid', 'Overnight'] };
  const RISK = { Equity: 'Very high', Debt: 'Moderate', Hybrid: 'High', ELSS: 'Very high', Index: 'Very high', Gold: 'High', Liquid: 'Low' };
  K.AMCS = AMCS; K.CATS = CATS; K.RISK = RISK;
  let sd = 11; const rn = () => { sd = (sd * 16807) % 2147483647; return (sd - 1) / 2147483646 };
  const F = []; let fi = 0;
  for (const c of CATS) for (const s of SUB[c]) for (let k = 0; k < (c === 'Equity' ? 3 : 2); k++) {
    const a = AMCS[Math.floor(rn() * 6)], b = { Equity: 14, Debt: 7, Hybrid: 11, ELSS: 14, Index: 12.5, Gold: 12, Liquid: 6.6 }[c], v = { Equity: 6, Debt: 1, Hybrid: 3.5, ELSS: 6, Index: 4, Gold: 6, Liquid: .3 }[c];
    F.push({ id: ++fi, name: `${a} ${s} Fund`, amc: a, cat: c, sub: s, risk: RISK[c], r1: +(b - 7 + rn() * v * 2 - v * .6).toFixed(2), r3: +(b + rn() * v - v * .4).toFixed(2), r5: +(b - 1 + rn() * v * .8).toFixed(2), rating: 1 + Math.floor(rn() * 5), nav: +(12 + rn() * 190).toFixed(3), aum: Math.round(900 + rn() * 80000), exp: +(.45 + rn() * 1.3).toFixed(2), minsip: rn() > .45 ? 500 : 1000, age: 2 + Math.floor(rn() * 18), inv: +(2 + rn() * 30).toFixed(1), mgr: ['A. Krishnan', 'S. Iyer', 'R. Menon', 'P. Rao', 'K. Natarajan', 'V. Sharma'][Math.floor(rn() * 6)] });
  }
  F.forEach(f => { if (f.r3 > 14 && f.rating < 4) f.rating = 4 });
  K.F = F;
  K.SEL = F.filter(f => ['Equity', 'Hybrid', 'ELSS'].includes(f.cat)).sort((a, b) => b.r3 - a.r3).slice(0, 8).map(f => f.id);
  K.fund = id => F.find(f => f.id === id) || F[0];
  /* daily NAV series, deterministic per fund */
  K.navSeries = (f, d) => {
    const keep = sd; sd = f.id * 977 + 13; const vol = { Equity: .011, Debt: .0012, Hybrid: .006, ELSS: .011, Index: .009, Gold: .008, Liquid: .0002 }[f.cat]; let v = 1; const p = [], dr = Math.pow(1 + f.r5 / 100, 1 / 365);
    for (let i = 0; i <= d; i++) { v *= dr * (1 + (rn() - .5) * vol * 2); p.push(v) } const k = f.nav / p[p.length - 1]; sd = keep; return p.map(x => x * k);
  };
  K.sparkFor = (f, n = 24) => { const s = K.navSeries(f, 365), out = []; for (let i = 0; i < n; i++) out.push(s[Math.round(i / (n - 1) * 365)]); return out };

  /* ---------- editorial ---------- */
  K.ARTICLES = [
    { id: 1, cat: 'Market notes', title: 'Markets fell 6% this month. Here is why we are not touching your SIPs.', dek: 'A falling market is the only time SIPs buy more for the same money. The hard part is not selling.', date: '12 October 2026', mins: 4, by: 'Research desk', body: ['Every few months the market gives families a reason to open the app and check. This month it was a 6% drop in the Nifty 50, driven by global bond yields and a weaker rupee. By the second week our phones were busy with the same question: should I stop my SIP?', 'The short answer is no, and the reason is arithmetic rather than optimism. A SIP buys a fixed rupee amount each month. When prices fall, that amount buys more units. Over a long period those cheaper units are what lift your average cost below the average price. Stopping the SIP in a falling market means skipping exactly the purchases that do the most work.', 'Consider two investors who each put ₹10,000 a month into the same flexi cap fund for five years that included a 25% fall. The one who paused for six months during the fall finished with roughly 9% less than the one who carried on, even though both put in nearly the same amount overall.', 'None of this means markets will recover next month. They may not. It means that your plan was built for a 15-year goal, and a six-week drop does not change the 15 years. If your goal is closer than three years, that is a different conversation, and it is the one your advisor will bring up before you have to.'], take: ['SIPs buy more units when prices fall', 'Pausing in a fall costs more than the fall itself', 'Goals under 3 years should not be in equity at all'] },
    { id: 2, cat: 'Research', title: 'Debt funds or fixed deposits, after the latest tax changes', dek: 'The gap has narrowed. For some investors, a deposit is now the simpler answer.', date: '5 October 2026', mins: 6, by: 'Research desk', body: ['For years the argument for debt funds over deposits rested on tax. Indexation brought the effective rate down for anyone holding longer than three years. That advantage has gone. Gains on most debt funds are now taxed at your slab rate, exactly like deposit interest.', 'What remains is flexibility. A deposit locks your money for a term; breaking it costs a penalty. A debt fund can be redeemed any working day and you only pay tax when you sell, so you control which financial year the income lands in. For someone close to a tax slab boundary, that control is worth something.', 'Where deposits win now is simplicity and certainty. A fixed rate, a known maturity, and no mark-to-market movement. For an emergency fund that you need to be certain of, we have started recommending liquid funds for the first three months and a ladder of deposits for the rest.', 'For money you will need in one to three years, our research committee still prefers short-duration and corporate bond funds, mainly for the ability to redeem in part. It is a closer call than it used to be.'], take: ['Debt funds and FDs are now taxed alike', 'Funds still win on flexibility and timing of tax', 'Use a deposit ladder for the stable part of an emergency fund'] },
    { id: 3, cat: 'Basics', title: 'How much should sit in your emergency fund?', dek: 'The usual answer is six months of expenses. The better answer depends on how your income arrives.', date: '28 September 2026', mins: 3, by: 'Priya Subramanian', body: ['Six months of expenses is a good starting point, and it is where most advisors begin. But it is a rule of thumb, and the right number for you depends on three things: how steady your income is, how many people depend on it, and what you would have to pay for whether you work or not.', 'A salaried person in a stable industry with a working spouse may be comfortable with four months. A freelancer, or a single-income family with ageing parents, should think of nine to twelve. Count only essentials: rent or EMI, groceries, school fees, insurance premiums and utilities.', 'Keep it where you can reach it the same day. Liquid funds, a sweep-in fixed deposit or a savings account are all fine. This money is not there to grow. Its job is to make sure that a hospital bill or a job loss never forces you to sell your long-term investments at the wrong moment.'], take: ['Start at six months of essential expenses', 'Freelancers and single-income homes need nine to twelve', 'This money is for safety, not returns'] },
    { id: 4, cat: 'Outlook', title: 'What we are watching this quarter', dek: 'Three things worth knowing about, and two we are deliberately ignoring.', date: '1 October 2026', mins: 5, by: 'Research desk', body: ['Each quarter our research committee writes down what it thinks matters and, just as importantly, what it thinks is noise. This quarter, three things made the first list.', 'First, corporate earnings growth has slowed to single digits for the first time in six quarters. Valuations in mid and small caps have not adjusted, which is why we have trimmed new SIP allocations to those categories by five percentage points.', 'Second, the yield curve has steepened. Longer-duration bonds now pay noticeably more than short ones, which makes a case for adding a little duration for goals more than three years away. Third, gold has quietly outperformed equity over twelve months, and rebalancing back to target will sell some of it.', 'We are ignoring monthly inflation prints and daily FII flow numbers. Both move headlines and neither has told us anything useful about a ten-year outcome.'], take: ['Earnings slowdown: trimmed mid and small cap SIP additions', 'Steeper yield curve: modest duration for 3+ year goals', 'Ignoring monthly CPI and daily FII flows'] },
    { id: 5, cat: 'Basics', title: 'Direct plan or regular plan? What the difference actually costs', dek: 'A 0.8% difference in annual cost sounds small. Over twenty years it is not.', date: '20 September 2026', mins: 5, by: 'Research desk', body: ['Every mutual fund comes in two versions: a direct plan, bought without an intermediary, and a regular plan, which includes a distributor commission inside the expense ratio. The direct plan costs less. Always. That is the whole fact, and it deserves to be stated clearly.', 'On ₹10,000 a month for twenty years at 12% before costs, a 0.8% yearly difference becomes roughly ₹14 lakh in final value. That is not a rounding error, and anyone telling you otherwise is selling you something.', 'So why would anyone use a regular plan? The honest answer is that some people value having a person to call, a plan, and someone to stop them from making a mistake in March 2020. If that is worth the cost to you, a regular plan through an advisor can be good value. If you only need the transaction, go direct.', 'We offer both, and we will tell you which one we think you need in the first conversation.'], take: ['Direct plans are always cheaper', 'The gap compounds to lakhs over twenty years', 'Pay for advice only if you will actually use it'] },
    { id: 6, cat: 'Research', title: 'What a 20% fall does to a retirement plan, year by year', dek: 'We ran the numbers on four retirement dates. The one that mattered was not the one you would guess.', date: '14 September 2026', mins: 7, by: 'Research desk', body: ['Sequence risk is the idea that when the fall happens matters more than how big it is. A 20% fall at 30 is a gift. At 59, it can change the rest of your life. We tested this with four retirement dates and the same 20% fall.', 'For someone retiring in five years, a fall of that size in the final year of saving cuts the sustainable monthly withdrawal by about 18%. The same fall in the first year of retirement cuts it by 23%. The second is worse because withdrawals then sell units at the bottom.', 'The practical response is a bucket approach: three years of expenses in debt funds, the rest in equity. In the fall, you draw from debt and leave equity alone to recover. The cost is a slightly lower expected return. The benefit is not having to sell at the worst time.'], take: ['Timing of a fall matters more than its size', 'Keep three years of spending in debt funds before retiring', 'Draw from debt in a fall and let equity recover'] }
  ];

  K.VOICES = [
    { n: 'Karthik Raman', p: 'Chennai · investing since 2019', g: "Daughter's education", q: 'My advisor talked me out of selling everything in March 2020. That one phone call is the reason my daughter’s education fund is on track today.', a: 0, big: '+112%', bl: 'since Mar 2020' },
    { n: 'Meena Sundaram', p: 'Coimbatore · retired teacher', g: 'Monthly income', q: 'I wanted a monthly income without touching the principal. They set up a withdrawal plan and explained every rupee of tax on it before I signed.', a: 1, big: '₹38,000', bl: 'monthly, tax-aware' },
    { n: 'Arvind & Latha Nair', p: 'Bengaluru · two goals', g: 'House + son’s college', q: 'Separate portfolios for the house and for our son made it obvious when we were drifting. The quarterly calls keep us honest, and a little embarrassed.', a: 2, big: '2 of 2', bl: 'goals on track' },
    { n: 'Divya Krishnamurthy', p: 'Hyderabad · product designer', g: 'First SIP at 27', q: 'I opened the account on my phone during lunch and had a plan by the time I got home. Nobody tried to sell me anything I did not ask about.', a: 3, big: '14 min', bl: 'to first SIP' }
  ];

  K.BONDS = [
    ['Coromandel Finance', 'A+', 'Secured', 10.85, '2 yrs 4 mo', 10045, 'Monthly', 28], ['Palar Housing Finance', 'AA−', 'Secured', 10.2, '3 yrs 1 mo', 100250, 'Quarterly', 37], ['Nilgiri Capital', 'BBB+', 'Secured', 11.4, '1 yr 8 mo', 99870, 'Monthly', 20], ['Vaigai Small Finance Bank', 'A', 'Unsecured', 10.6, '4 yrs 9 mo', 104100, 'Yearly', 57],
    ['State Power Utility', 'AAA', 'Secured', 8.15, '7 yrs 2 mo', 10210, 'Half-yearly', 86], ['Kaveri Microfinance', 'A−', 'Secured', 11.1, '1 yr 2 mo', 100900, 'Monthly', 14]
  ];

  K.FAQ = {
    'Getting started': [['How much do I need to start?', 'Most funds accept a SIP from ₹500 or ₹1,000 a month. A one-time investment usually starts at ₹1,000. There is no minimum balance with us.'], ['What do I need to open an account?', 'Your PAN, Aadhaar linked to your mobile number, and a bank account. KYC is done online through DigiLocker with a selfie and a signature. Most people finish in under fifteen minutes.'], ['Can NRIs invest?', 'Yes, with an NRE or NRO account. A few fund houses do not accept investors living in the US or Canada, and we will tell you which ones before you start.']],
    'Money and safety': [['Where does my money actually go?', 'Straight from your bank account to the mutual fund company. Units are held in your name with the fund house’s registrar. We never hold your money, and we cannot move it anywhere but back to your own bank account.'], ['Can I take my money out whenever I want?', 'Most funds can be redeemed on any working day, with money in your bank in one to three days. Tax-saving ELSS funds are locked in for three years, and a few debt funds have exit charges within a month.'], ['What happens if Kosha shuts down?', 'Nothing happens to your investments. They are held with the fund houses in your name, not on our books. You would keep your folios and could continue with any other distributor or go direct.']],
    'Advice and fees': [['How do you get paid?', 'Placeholder: describe the client’s pricing model here. See the pricing page for the illustrative structure used in this demo.'], ['Do I have to talk to an advisor?', 'No. You can build and run everything yourself online. The advisor is there if you want a plan, a second opinion or someone to talk you out of a mistake.'], ['How often will we review my plan?', 'Every quarter by default, and any time something changes in your life or in the market that affects a goal.']],
    'Tax': [['How are mutual fund gains taxed?', 'Equity funds held over a year pay long-term gains tax above ₹1.25 lakh a year of gains; shorter holds pay short-term rates. Debt funds are taxed at your slab rate. Your capital gains statement shows exactly what is due.'], ['Does ELSS really save tax?', 'Up to ₹1.5 lakh a year under Section 80C, under the old tax regime. If you have chosen the new regime, 80C does not apply to you and an ELSS fund is only worth buying on its merits.']]
  };
  K.faqHTML = (cat) => `<div class="acc">${Object.entries(K.FAQ).filter(([k]) => !cat || k === cat).flatMap(([, v]) => cat ? v : v.slice(0, 2)).map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div>`;

  K.NAV = [
    { k: 'Invest', cols: [
      { h: 'Products', items: [['Mutual funds', '1,500+ funds. SIP from ₹500.', 'chart', '#/mutual-funds'], ['Bonds and deposits', 'Rated issuers, yields up to 11%.', 'bank', '#/fixed-income'], ['NPS', 'Retirement plus an extra ₹50,000 deduction.', 'sunrise', '#/fixed-income/nps'], ['Insurance', 'Term and health cover.', 'shield', '#/fixed-income/insurance']] },
      { h: 'Ways to invest', items: [['SIP and step-up SIP', 'Invest every month, grow it yearly.', 'refresh', '#/mutual-funds/sip'], ['Lump sum', 'One-time investment with a plan.', 'wallet', '#/mutual-funds/sip'], ['Tax saving (ELSS)', 'Save up to ₹46,800 under 80C.', 'leaf', '#/calculators/tax'], ['Kosha Select', 'Eight funds our team would buy.', 'award', '#/mutual-funds/select']] }],
      feat: { t: 'Not sure where to start?', d: 'Answer six questions and get a written plan from a named advisor, free.', cta: 'Plan my goals', h: '#/goals', ic: 'sparkle' } },
    { k: 'Plan', cols: [{ h: 'Plan a goal', items: [["Child's education", 'Fees that rise faster than prices.', 'cap', '#/goals/edu'], ['Retirement', 'Replace your salary for 25 years.', 'sunrise', '#/goals/ret'], ['A home of your own', 'Down payment, sorted.', 'home', '#/goals/home']] }, { h: 'More goals', items: [['Emergency money', 'Six months, same-day access.', 'shield', '#/goals/emg'], ['A family holiday', 'No credit card bill after.', 'plane', '#/goals/trip'], ['Long-term wealth', 'No date, just growth.', 'trend', '#/goals/wealth']] }],
      feat: { t: 'See the monthly number', d: 'Tell us the goal and the date. We work backwards to the SIP.', cta: 'Open the planner', h: '#/goals', ic: 'target' } },
    { k: 'Tools', cols: [{ h: 'Calculators', items: [['SIP calculator', 'What a monthly amount grows to.', 'refresh', '#/calculators/sip'], ['Step-up SIP', 'Raise it a little every year.', 'trend', '#/calculators/stepup'], ['Lump sum', 'One cheque, many years.', 'wallet', '#/calculators/lump']] }, { h: 'More tools', items: [['SWP', 'Monthly income from savings.', 'download', '#/calculators/swp'], ['Retirement', 'Corpus and monthly SIP needed.', 'sunrise', '#/calculators/retire'], ['Tax saving', 'What 80C actually saves you.', 'percent', '#/calculators/tax']] }],
      feat: { t: 'Compare funds side by side', d: 'Pick up to three funds and see returns, costs and risk together.', cta: 'Log in to compare', login: 1, ic: 'compare' } },
    { k: 'Learn', cols: [{ h: 'Research desk', items: [['Market notes', 'What moved and what we did.', 'chart', '#/research'], ['Basics', 'Plain-language money guides.', 'book', '#/research'], ['Outlook', 'Our quarterly view.', 'eye', '#/research']] }, { h: 'Read first', items: [['Why we are not touching your SIPs', '4 minute read', 'doc', '#/research/read/1'], ['Direct or regular plan?', '5 minute read', 'doc', '#/research/read/5']] }],
      feat: { t: 'Monday Money Note', d: 'One email a week. Five minutes. No predictions, no hot tips.', cta: 'Subscribe', h: '#/research', ic: 'mail' } },
    { k: 'Company', cols: [{ h: 'Kosha', items: [['About us', 'Who we are and how we work.', 'users', '#/about'], ['How we earn', 'Pricing, with no small print.', 'coin', '#/pricing'], ['Talk to an advisor', 'Book a call or visit us.', 'phone', '#/contact']] }, { h: 'Trust', items: [['Security', 'How your money and data are kept safe.', 'lock', '#/about/security'], ['Grievance redressal', 'Escalation, step by step.', 'scale', '#/about/grievance'], ['Careers', 'Come help families invest well.', 'sparkle', '#/about/careers']] }],
      feat: { t: 'We answer the phone', d: 'Real people, Monday to Saturday, 9am to 7pm. Usually within three rings.', cta: '1800 XXX XXXX', h: '#/contact', ic: 'phone' } }
  ];
})(window.K);
