/* Kosha Wealth — public pages, part 1: Mutual funds, Fixed income, Goals */
(function (K) {
  const { $, $$, ico, inr, L, F } = K;
  K.subnav = items => `<div class="subnav"><div class="w"><div class="sn-in">${items.map((s, i) => `<button data-scroll="${s[1]}"${i === 0 ? ' class="on"' : ''}>${s[0]}</button>`).join('')}</div></div></div>`;
  K.wireSubnav = () => {
    const bs = $$('.subnav button'); if (!bs.length || !window.IntersectionObserver) return;
    const map = bs.map(b => $(`[data-anchor="${b.dataset.scroll}"]`)).filter(Boolean);
    const io = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) { const k = map.indexOf(e.target); bs.forEach((b, i) => b.classList.toggle('on', i === k)) } }), { rootMargin: '-30% 0px -60% 0px' }); map.forEach(m => io.observe(m));
    const top = () => { if (!$('.subnav')) return removeEventListener('scroll', top); if (scrollY < 250) bs.forEach((b, i) => b.classList.toggle('on', i === 0)) }; addEventListener('scroll', top, { passive: true });
  };
  document.addEventListener('click', e => { const b = e.target.closest('[data-scroll]'); if (b) { const t = $(`[data-anchor="${b.dataset.scroll}"]`); if (t) { t.scrollIntoView({ behavior: 'smooth', block: 'start' }); if (b.dataset.pick) b.dispatchEvent(new CustomEvent('pick', { bubbles: true })) } } });
  const cta = (t, s) => `<section class="sec dark cta2"><div class="w"><h2 data-r>${t}</h2><div class="acts" data-r style="--d:.1s"><button class="b b-gold b-lg" data-login>${s || 'Open an account'}${ico('arrow', 'go')}</button><a class="b b-glass b-lg" href="#/contact">Talk to an advisor</a></div></div></section>`;
  K.cta2 = cta;
  const pageHead = (eyebrow, h1, lede, extra = '') => `<section class="ph-hero"><div class="w"><span class="eyebrow">${eyebrow}</span><h1 data-r>${h1}</h1><p class="lede" data-r style="--d:.08s">${lede}</p>${extra}</div></section>`;
  K.pageHead = pageHead;

  /* ======================= MUTUAL FUNDS ======================= */
  const TYPES = [
    { k: 'Liquid', c: '#12A3AE', inv: 'Very short-term debt and money-market instruments', risk: 1, hz: [0, 1], hzl: 'Days to a year', ret: 6, rr: '5–7%', best: 'Emergency money, and cash you will need soon', eg: 'Liquid' },
    { k: 'Debt', c: '#6B63D8', inv: 'Government and company bonds of varying lengths', risk: 2, hz: [1, 4], hzl: '1 to 4 years', ret: 7, rr: '6–8%', best: 'Money needed in a few years, with less bumpiness', eg: 'Short Duration' },
    { k: 'Hybrid', c: '#E8A317', inv: 'Shares and bonds together, rebalanced for you', risk: 3, hz: [3, 7], hzl: '3 to 7 years', ret: 10, rr: '8–12%', best: 'First-time investors and middle-distance goals', eg: 'Balanced Advantage' },
    { k: 'Gold', c: '#B97F08', inv: 'Gold held through a regulated fund', risk: 3, hz: [5, 10], hzl: '5 years or more', ret: 8.5, rr: '7–10%', best: 'Spreading risk when shares and bonds both wobble', eg: 'Gold' },
    { k: 'Index', c: '#2F3A9E', inv: 'Every company in an index like the Nifty 50, at very low cost', risk: 4, hz: [7, 10], hzl: '7 years or more', ret: 12, rr: '10–14%', best: 'Long goals, with the lowest fees in the market', eg: 'Nifty 50 Index' },
    { k: 'ELSS', c: '#14804F', inv: 'Shares, with a three-year lock-in and 80C tax saving', risk: 5, hz: [5, 10], hzl: '5 years or more', ret: 13, rr: '11–15%', best: 'Saving tax while building long-term wealth', eg: 'Tax Saver' },
    { k: 'Equity', c: '#D9573B', inv: 'Shares of companies, from large and steady to small and fast', risk: 5, hz: [7, 10], hzl: '7 years or more', ret: 14, rr: '11–16%', best: 'Retirement, children’s education, long-term wealth', eg: 'Flexi Cap' }
  ];
  const BUB = { Liquid: [11, 76, 96], Debt: [31, 60, 108], Hybrid: [51, 45, 112], Gold: [70, 68, 90], Index: [83, 42, 98], ELSS: [66, 22, 94], Equity: [86, 12, 104] };
  const SCEN = {
    steady: ['Steady climb', Array.from({ length: 60 }, () => .0095)],
    crash: ['Crash in year one', Array.from({ length: 60 }, (_, m) => m < 10 ? -.028 : m < 14 ? .01 : .0135)],
    late: ['Rise, then a long fall', Array.from({ length: 60 }, (_, m) => m < 30 ? .02 : m < 44 ? -.028 : .012)]
  };

  K.pages['/mutual-funds'] = () => {
    const h = `
<section class="mf-hero"><div class="w"><div>
  <span class="eyebrow">Mutual funds</span><h1 data-r>Mutual funds, chosen <em>with a reason</em>.</h1>
  <p class="lede" data-r style="--d:.08s">Every fund we suggest comes with a written explanation of why it fits your goal, and a note on when we would replace it.</p>
  <div class="acts" data-r style="--d:.16s"><button class="b b-go b-lg" data-login>Start a SIP${ico('arrow', 'go')}</button><button class="b b-line b-lg" data-scroll="types">Which type is for me?</button></div>
  <div class="mf-facts n" data-r style="--d:.24s"><div><b data-count="1512" data-fmt="in">0</b>funds to choose from</div><div><b>₹500</b>SIP, to begin</div><div><b>40+</b>fund houses</div></div></div>
  <div class="spec" data-r="s" aria-label="Fund types by risk and time horizon"><div class="spec-in"><span class="ax y">Risk ↑</span><span class="ax x">Time you can leave it alone →</span>${['Days', '1 yr', '3 yrs', '7 yrs', '10+'].map((t, i) => `<span class="tk" style="left:${6 + i * 22}%">${t}</span>`).join('')}${TYPES.map((t, i) => { const b = BUB[t.k]; return `<button class="bub" data-scroll="types" data-pick="${t.k}" style="left:${b[0]}%;top:${b[1]}%;width:${b[2]}px;height:${b[2]}px;background:${t.c};animation-delay:${-i * 1.3}s" aria-label="${t.k} funds">${t.k}</button>` }).join('')}</div></div>
</div></section>
${K.subnav([['Types', 'types'], ['SIP or lump sum', 'sip'], ['Kosha Select', 'select'], ['Costs', 'costs'], ['Questions', 'faq']])}

<section class="sec" style="padding-bottom:40px"><div class="w"><div class="why6">
  ${[['Spread across hundreds of companies', 'One bad stock cannot sink your savings.'], ['Managed full time', 'Fund managers research markets so you do not have to.'], ['Start with ₹500', 'Raise the amount as your income grows.'], ['Withdraw when you need to', 'Money reaches your bank in one to three working days.'], ['Fully transparent', 'Prices published daily, holdings every month.'], ['Tax-aware', 'Tax only when you sell, and ELSS saves tax under 80C.']].map((w, i) => `<div data-r style="--d:${(i % 3) * .08}s"><span class="no">0${i + 1}</span><h3>${w[0]}</h3><p>${w[1]}</p></div>`).join('')}</div></div></section>

<section class="sec" data-anchor="types"><div class="w"><div class="shead"><span class="eyebrow">Fund types</span><h2 data-r>Seven kinds of fund. <em>One</em> question decides.</h2><p class="lede" data-r>When will you need the money? The answer narrows seven types down to two or three.</p></div>
  <div class="tx" id="tx"><div class="tx-l" id="txl" role="tablist">${TYPES.map((t, i) => `<button role="tab" data-t="${t.k}" aria-selected="${i === 0}"><i style="background:${t.c}"></i><b>${t.k}</b><span>${t.hzl}</span>${ico('chevR')}</button>`).join('')}</div><div class="tx-r" id="txr"></div></div></div></section>

<section class="sec cream" data-anchor="sip"><div class="w"><div class="shead row"><div><span class="eyebrow">SIP or lump sum</span><h2 style="margin-top:18px" data-r>Same money. <em>Different</em> journeys.</h2></div><p class="lede" data-r>A SIP spreads your buying across months. A lump sum buys everything on day one. Which one finishes ahead depends entirely on what the market does next, which nobody knows.</p></div>
  <div class="sv"><div class="sv-c"><div class="seg" id="svS" role="group" aria-label="Market scenario">${Object.entries(SCEN).map(([k, v], i) => `<button data-k="${k}" aria-pressed="${i === 0}">${v[0]}</button>`).join('')}</div><div id="svCh" style="margin-top:26px"></div><div class="legend" style="margin-top:10px"><span><i style="background:var(--teal)"></i>₹10,000 a month for 5 years</span><span><i style="background:var(--gold)"></i>₹6 lakh invested on day one</span></div></div>
  <div class="sv-r"><div class="sv-res" id="svR"></div><p class="sm muted" id="svN" style="margin-top:18px"></p></div></div></div></section>

<section class="sec" data-anchor="select"><div class="w"><div class="sel2"><div><span class="eyebrow">Kosha Select</span><h2 style="margin:18px 0 20px" data-r>What a fund has to <em>prove</em>.</h2><p class="lede" data-r>Four tests, applied every quarter. A fund that fails one is put on watch; two, and we tell you in writing and suggest a replacement.</p>
  <div class="crit">${[['Consistency', 'Top half of its category in at least 7 of the last 10 rolling 3-year periods.'], ['Cost', 'Expense ratio in the cheapest third of its category.'], ['People and process', 'Same lead manager for 3+ years, with a written process we can test.'], ['Downside', 'Falls no more than its category in a bad year, and recovers sooner.']].map((c, i) => `<div data-r style="--d:${i * .07}s"><span class="no">${i + 1}</span><div><b>${c[0]}</b><p>${c[1]}</p></div></div>`).join('')}</div></div>
  <div class="card-sc" data-r="rt">${(() => { const f = F[K.SEL[0] - 1]; return `<div class="sc-h"><div><span class="pill gold">${ico('award')} Kosha Select</span><h3 style="margin:12px 0 4px;font-family:var(--serif);font-weight:400;font-size:1.7rem">${f.name}</h3><small class="muted">${f.cat} · ${f.sub} · ${f.amc} Mutual Fund</small></div><div class="sc-r n"><b>${f.r3.toFixed(1)}%</b><small>3-year, yearly</small></div></div>${[['Consistency', 92], ['Cost', 88], ['People and process', 78], ['Downside', 85]].map(s => `<div class="sc-b"><span>${s[0]}</span><div><i style="width:${s[1]}%"></i></div><b class="n">${s[1]}</b></div>`).join('')}<div class="sc-f">${K.sparkFor(f) && K.spark(K.sparkFor(f, 40), { w: 300, h: 56, fill: 1 })}<small class="muted">Price, last 12 months · sample data</small></div>` })()}</div></div>
  <div class="lb" style="margin-top:56px" data-r><div class="lb-h"><h3 style="font-family:var(--serif);font-weight:400;font-size:1.6rem">This quarter’s eight</h3><span class="fine">Sample data</span></div><div class="lb-hd"><span>#</span><span>Fund</span><span>Trend</span><span>1 year</span><span>3 years</span><span>5 years</span><span></span></div><div id="selL"></div></div></div></section>

<section class="sec dark" data-anchor="costs"><div class="w"><div class="cs"><div><span class="eyebrow gold">What it costs</span><h2 style="margin:18px 0 20px" data-r>A <em>0.8%</em> difference doesn’t sound like much.</h2><p class="lede" data-r>Direct plans cost less than regular plans, always. Whether an advisor is worth the difference is a fair question, and one we would rather you ask than not.</p>
  <div class="sls" id="csS" style="margin-top:36px"><div class="sl"><div class="top"><label for="csA">Monthly SIP</label><span class="val n" id="csAv"></span></div><input type="range" id="csA" min="2000" max="100000" step="1000" value="10000"></div><div class="sl"><div class="top"><label for="csY">For how long</label><span class="val n" id="csYv"></span></div><input type="range" id="csY" min="5" max="35" value="20"></div></div></div>
  <div class="tm-out" data-r="rt"><div class="lab">The gap after <span id="csY2"></span></div><div class="val n" id="csV"></div><div id="csCh"></div><div class="legend" style="margin-top:10px"><span><i style="background:#7FD8E0"></i>Direct plan, 0.6% cost</span><span><i style="background:#E8A317"></i>Regular plan, 1.4% cost</span></div><div class="tm-chips n"><div>Direct plan<b id="csD"></b></div><div>Regular plan<b id="csR"></b></div><div>Gap<b id="csG"></b></div></div></div></div>
  <div class="layers" data-r><h3 style="font-family:var(--serif);font-weight:400;font-size:1.7rem;color:#fff;margin-bottom:6px">Every layer of cost, named</h3><div class="ly">${[['Expense ratio', '0.1% – 2.2% a year', 'Charged inside the fund. Already reflected in the price you see.'], ['Distributor commission', '0% – 1% a year', 'Inside a regular plan’s expense ratio. Zero in a direct plan.'], ['Exit load', '0% – 1%', 'Only if you sell within a short window, usually a year.'], ['Tax', '12.5% / 20% / slab', 'On gains, when you sell. Depends on fund type and how long you held.'], ['Kosha advisory fee', 'See pricing', 'Only if you choose advice. Charged openly, never hidden in the fund.']].map(r => `<div><b>${r[0]}</b><span class="n">${r[1]}</span><p>${r[2]}</p></div>`).join('')}</div><a class="lnk" href="#/pricing" style="color:var(--gold);margin-top:22px">How we earn ${ico('arrow')}</a></div></div></section>

<section class="sec" data-anchor="faq"><div class="w"><div class="fq"><div class="fq-l"><span class="eyebrow">Common questions</span><h2 style="margin:18px 0 0" data-r>Before you <em>start</em>.</h2></div><div data-r>${K.faqHTML('Money and safety').replace('<div class="acc">', '<div class="acc">') + `<div style="height:0"></div>`}</div></div></div></section>
${cta('Start with a single SIP, or a lump sum.', 'Start investing')}`;
    return {
      t: 'Mutual funds', h, w() {
        K.wireSubnav();
        let sel = TYPES[0].k; const tx = k => { sel = k; const t = TYPES.find(x => x.k === k); $$('#txl button').forEach(b => b.setAttribute('aria-selected', b.dataset.t === k)); const sample = F.filter(f => f.cat === t.k).sort((a, b) => b.r5 - a.r5).slice(0, 2), yrs = Math.max(t.hz[1], 3), v = K.sipFV(10000, yrs, t.ret);
          $('#txr').innerHTML = `<div class="tx-rh"><span class="pill" style="background:${t.c};color:#fff">${t.k}</span><h3>${t.inv}</h3></div><div class="tx-grid"><div><small>Risk level</small><div class="rmeter">${[1, 2, 3, 4, 5].map(i => `<i style="${i <= t.risk ? 'background:' + t.c : ''}"></i>`).join('')}</div><b>${['Very low', 'Low to moderate', 'Moderate to high', 'High', 'Very high'][t.risk - 1]}</b></div><div><small>Typical yearly return, long run</small><b class="big n">${t.rr}</b><span class="xs muted">Not guaranteed. Illustrative.</span></div></div>
          <div class="hzl"><small>Best for money you will need in</small><div class="hz-bar"><span style="left:${t.hz[0] * 10}%;width:${(t.hz[1] - t.hz[0]) * 10}%;background:${t.c}"></span>${[0, 1, 3, 5, 7, 10].map(y => `<em style="left:${y * 10}%">${y === 10 ? '10+' : y}</em>`).join('')}</div></div>
          <div class="tx-ex"><div><small>Good for</small><p>${t.best}</p></div><div><small>₹10,000 a month for ${yrs} years could become</small><p class="n" style="font-family:var(--serif);font-size:1.9rem;color:var(--ink);letter-spacing:-.03em">${L(v)}</p></div></div>
          <div class="tx-f"><small>Sample funds</small>${sample.map(f => `<button class="lnk" data-f="${f.id}">${f.name}${ico('arrow')}</button>`).join('')}</div>` };
        $('#txl').onclick = e => { const b = e.target.closest('button'); if (b) tx(b.dataset.t) }; document.addEventListener('pick', function h(e) { if (!$('#txl')) return document.removeEventListener('pick', h); tx(e.target.dataset.pick) }); tx(sel);
        /* sip vs lump */
        let sc = 'steady'; const sv = () => { const r = SCEN[sc][1], a = 10000, s = [0], l = [a * 60]; let v = 0, lv = a * 60; r.forEach((x, m) => { v = (v + a) * (1 + x); lv *= (1 + x); s.push(v); l.push(lv) });
          const sd = new Date(2026, 9, 1); K.chart($('#svCh'), { h: 300, series: [{ name: 'SIP', data: s, color: 'var(--teal)', fill: 'color-mix(in srgb,var(--teal) 10%,transparent)' }, { name: 'Lump sum', data: l, color: 'var(--gold)' }], x: i => i ? 'Year ' + (i / 12).toFixed(0) : 'Start', tipx: i => 'Month ' + i, fmt: K.L, yfmt: K.short, ymin: 0, xticks: 6 });
          const end = [s[60], l[60]], win = end[0] > end[1] ? 'SIP' : 'Lump sum'; $('#svR').innerHTML = `<div><small>SIP finishes at</small><b class="n" style="color:var(--teal)">${L(end[0])}</b></div><div><small>Lump sum finishes at</small><b class="n" style="color:var(--gold-2)">${L(end[1])}</b></div><div class="win"><small>Ahead by</small><b class="n">${L(Math.abs(end[0] - end[1]))}</b><span class="pill ${win === 'SIP' ? '' : 'gold'}">${win} wins here</span></div>`;
          $('#svN').textContent = { steady: 'In a market that only goes up, money invested earliest wins. This is the case for a lump sum, and it is the one that almost never happens.', crash: 'When prices fall early, a SIP buys more units cheaply while the lump sum sits through the whole fall.', late: 'A long rise followed by a long fall rewards neither. The lump sum rides the rise further, then loses more of it.' }[sc] };
        $('#svS').onclick = e => { const b = e.target.closest('button'); if (!b) return; sc = b.dataset.k; $$('#svS button').forEach(x => x.setAttribute('aria-pressed', x === b)); sv() }; sv();
        /* leaderboard */
        K.leaderboard($('#selL'), K.SEL.map(i => F[i - 1]));
        /* costs */
        const cs = () => { const a = +$('#csA').value, y = +$('#csY').value, g = 12, dir = [], reg = []; for (let k = 0; k <= y; k++) { dir.push(K.sipFV(a, k, g - .6)); reg.push(K.sipFV(a, k, g - 1.4)) }
          $('#csAv').textContent = inr(a); $('#csYv').textContent = y + ' yrs'; $('#csY2').textContent = y + ' years'; $('#csV').textContent = L(dir[y] - reg[y]); $('#csD').textContent = L(dir[y]); $('#csR').textContent = L(reg[y]); $('#csG').textContent = L(dir[y] - reg[y]);
          K.chart($('#csCh'), { h: 220, series: [{ name: 'Direct', data: dir, color: '#7FD8E0', fill: 'rgba(127,216,224,.16)' }, { name: 'Regular', data: reg, color: '#E8A317', fill: 'rgba(232,163,23,.16)' }], x: i => 'Yr ' + i, tipx: i => 'After ' + i + ' years', xticks: 5 }) };
        ['#csA', '#csY'].forEach(s => $(s).oninput = cs); K.fillAll($('#csS')); cs();
      }
    };
  };

  /* ======================= FIXED INCOME ======================= */
  const RC = { AAA: '#14804F', 'AA−': '#0A8D99', 'A+': '#6B63D8', A: '#6B63D8', 'A−': '#E8A317', 'BBB+': '#D9573B' };
  const DEP = { 1: 7.6, 2: 8.0, 3: 8.5, 5: 8.3 };
  K.pages['/fixed-income'] = () => {
    const h = `
<section class="fi-hero dark"><div class="w"><div><span class="eyebrow gold">Bonds, deposits and more</span><h1 data-r>Steady interest, <em>in writing</em>.</h1><p class="lede" data-r style="--d:.08s">For the part of your money that should not surprise you. Rated bonds, company deposits, NPS and insurance, in the same account as your mutual funds.</p><div class="acts" data-r style="--d:.16s"><button class="b b-gold b-lg" data-login>Start investing${ico('arrow', 'go')}</button><button class="b b-glass b-lg" data-scroll="bonds">Browse bonds</button></div></div>
  <div class="yl" data-r="s"><div class="yl-h"><small>Yield by years to maturity</small><span class="pill gold">Live demo data</span></div>${[['1 yr', 8.4], ['2 yrs', 9.6], ['3 yrs', 10.2], ['5 yrs', 10.9], ['7 yrs', 11.4]].map((r, i) => `<div class="yl-r"><span>${r[0]}</span><div><i style="width:${r[1] / 12 * 100}%;animation-delay:${i * .12}s"></i></div><b class="n">${r[1]}%</b></div>`).join('')}<p class="fine" style="color:#8E93C0;margin-top:14px">Higher yield means higher credit risk. Sorted by rating on the page below.</p></div></div></section>
${K.subnav([['Bonds', 'bonds'], ['Deposits', 'deposits'], ['NPS', 'nps'], ['Insurance', 'insurance'], ['SIF', 'sif']])}

<section class="sec" data-anchor="bonds"><div class="w"><div class="shead row"><div><span class="eyebrow">Listed bonds</span><h2 style="margin-top:18px" data-r>Yield, risk and time, <em>on one page</em>.</h2></div><p class="lede" data-r>Every bubble is a bond. Further right means longer to run, higher means more interest. Colour is the credit rating.</p></div>
  <div class="bd-g"><div class="scat" data-r><div id="scat"></div><div class="legend" style="margin-top:12px">${[['AAA', '#14804F'], ['AA', '#0A8D99'], ['A', '#6B63D8'], ['BBB', '#D9573B']].map(r => `<span><i style="background:${r[1]}"></i>${r[0]}</span>`).join('')}</div></div>
  <div data-r="rt"><div class="chips" id="bdF" style="margin-bottom:12px">${['All', 'AAA and AA', 'Yield over 10%', 'Under 2 years', 'Monthly interest'].map((c, i) => `<button class="chip" data-f="${i}" aria-pressed="${i === 0}">${c}</button>`).join('')}</div><div id="bdL"></div></div></div>
  <p class="fine" style="margin-top:22px">Offered through a SEBI-registered Online Bond Platform Provider partner. Bonds carry credit, interest-rate and liquidity risk. Issuer names are fictional.</p></div></section>

<section class="sec cream" data-anchor="deposits"><div class="w"><div class="dp"><div><span class="eyebrow">Fixed deposits</span><h2 style="margin:18px 0 20px" data-r>Know the maturity amount <em>on day one</em>.</h2><p class="lede" data-r>Deposits from rated companies, only AA and above. Choose a tenure, choose how interest is paid, and see exactly what you will get.</p>
  <div class="sls" id="dpS" style="margin-top:34px"><div class="sl"><div class="top"><label for="dpA">Deposit amount</label><span class="val n" id="dpAv"></span></div><input type="range" id="dpA" min="25000" max="2500000" step="25000" value="500000"></div><div class="sl"><div class="top"><label>Tenure</label></div><div class="chips" id="dpT">${[1, 2, 3, 5].map(y => `<button class="chip" data-y="${y}" aria-pressed="${y === 3}">${y} year${y > 1 ? 's' : ''} · ${DEP[y]}%</button>`).join('')}</div></div><div class="sl"><div class="top"><label>Interest paid</label></div><div class="seg" id="dpP">${['At maturity', 'Quarterly', 'Monthly'].map((c, i) => `<button data-p="${i}" aria-pressed="${i === 0}">${c}</button>`).join('')}</div></div></div></div>
  <div class="dp-out" data-r="rt"><small class="muted" id="dpLb"></small><div class="big-rate n" id="dpV"></div><div class="dp-b"><div><i style="background:var(--ink)"></i>You deposit<b class="n" id="dpI"></b></div><div><i style="background:var(--gold)"></i>Interest<b class="n" id="dpG"></b></div></div><div class="dp-vs"><div class="rw"><span>This deposit</span><i id="dpB1"></i><b class="n" id="dpR1"></b></div><div class="rw"><span>Savings account</span><i id="dpB2" style="background:var(--rule-2)"></i><b class="n" id="dpR2"></b></div></div><p class="fine">Interest is taxable at your slab rate. Rates are illustrative. TDS applies above ₹40,000 of interest a year.</p></div></div></div></section>

<section class="sec" data-anchor="nps"><div class="w"><div class="shead row"><div><span class="eyebrow">NPS</span><h2 style="margin-top:18px" data-r>Two tax doors. <em>One</em> retirement pot.</h2></div><p class="lede" data-r>The National Pension System lets you save tax on top of the ₹1.5 lakh 80C limit, with some of the lowest fund costs in India. The catch is that the money stays put until 60.</p></div>
  <div class="nps"><div class="nps-t" data-r><h3 style="font-family:var(--serif);font-weight:400;font-size:1.7rem;margin-bottom:22px">What a ₹50,000 NPS contribution saves you</h3><div class="sl"><div class="top"><label>Your tax slab</label></div><div class="seg" id="npsS">${[10, 20, 30].map((s, i) => `<button data-s="${s}" aria-pressed="${s === 30}">${s}%</button>`).join('')}</div></div><div class="nps-bar"><div style="flex:3"><b>80C</b>₹1,50,000 · ELSS, PPF, EPF</div><div class="g" style="flex:1"><b>80CCD(1B)</b>₹50,000 · NPS only</div></div><div class="nps-r"><span>Extra tax saved each year</span><b class="n" id="npsV"></b></div><p class="fine">Old tax regime only, including 4% cess. Not tax advice.</p></div>
  <div class="life" data-r="rt"><h3 style="font-family:var(--serif);font-weight:400;font-size:1.7rem;margin-bottom:26px">The life of an NPS account</h3><div class="lf">${[['Now to 60', 'You contribute', 'From ₹1,000 a month. Choose your equity share, up to 75%.', 'var(--teal)'], ['At 60', 'You withdraw', 'Up to 60% of the pot as a lump sum, tax-free.', 'var(--gold)'], ['After 60', 'You draw a pension', 'At least 40% buys an annuity that pays every month for life.', 'var(--violet)']].map((s, i) => `<div><i style="background:${s[3]}"></i><small>${s[0]}</small><b>${s[1]}</b><p>${s[2]}</p></div>`).join('')}</div></div></div></div></section>

<section class="sec cream" data-anchor="insurance"><div class="w"><div class="ins"><div><span class="eyebrow">Insurance</span><h2 style="margin:18px 0 20px" data-r>So a bad year never has to <em>touch the plan</em>.</h2><p class="lede" data-r>A term plan protects the people who depend on your income. Health cover protects your savings from a hospital bill. We will help you size both, and then leave them alone.</p>
  <div class="sls" id="inS" style="margin-top:34px"><div class="sl"><div class="top"><label for="inI">Your yearly income</label><span class="val n" id="inIv"></span></div><input type="range" id="inI" min="3" max="100" value="15"></div><div class="sl"><div class="top"><label for="inL">Loans and liabilities</label><span class="val n" id="inLv"></span></div><input type="range" id="inL" min="0" max="200" value="30"></div><div class="sl"><div class="top"><label for="inE">Cover you already have</label><span class="val n" id="inEv"></span></div><input type="range" id="inE" min="0" max="200" value="25"></div></div></div>
  <div class="ins-o" data-r="rt"><div class="shield">${ico('shield')}</div><small>Suggested term cover</small><div class="serif n" id="inV"></div><p>That is roughly <b id="inX"></b> your yearly income, plus loans, less what you have. A rule of thumb to start the conversation, not a quote.</p><div class="ins-l"><div>${ico('check')}Term life, to age 60</div><div>${ico('check')}Health cover of at least ₹10 lakh for the family</div><div>${ico('check')}A separate top-up for parents</div></div><button class="b b-ink b-wide" data-toast="Quote request sent. An advisor will call (demo)">Get a quote${ico('arrow', 'go')}</button></div></div></div></section>

<section class="sec" data-anchor="sif"><div class="w"><div class="shead c"><span class="eyebrow">Specialised Investment Funds</span><h2 data-r>The step between a mutual fund and <em>a PMS</em>.</h2><p class="lede" data-r>A newer SEBI category for investors who want more than a plain mutual fund can do, without the ₹50 lakh minimum of a portfolio manager.</p></div>
  <div class="sif" data-r>${[['Mutual fund', 'From ₹500', 'Long-only, daily NAV, lowest cost.', 0], ['SIF', 'From ₹10 lakh', 'Can go long and short. Up to 25% in derivatives for hedging and return.', 1], ['PMS', 'From ₹50 lakh', 'A portfolio in your own name, built just for you.', 0]].map((s, i) => `<div class="${s[3] ? 'hl' : ''}"><span class="no">0${i + 1}</span><h3>${s[0]}</h3><b class="n">${s[1]}</b><p>${s[2]}</p>${s[3] ? '<span class="pill gold">New since 2025</span>' : ''}</div>`).join('')}</div></div></section>
${cta('Safe money deserves a plan too.', 'Open an account')}`;
    return {
      t: 'Bonds, deposits and more', h, w() {
        K.wireSubnav();
        /* bonds */
        let bf = 0; const bl = () => { const B = K.BONDS.map((b, i) => ({ b, i })).filter(({ b }) => [() => 1, () => ['AAA', 'AA−'].includes(b[1]), () => b[3] > 10, () => b[7] < 24, () => b[6] === 'Monthly'][bf]());
          $('#bdL').innerHTML = B.map(({ b }) => `<div class="bdr n"><span class="rt-b" style="background:${RC[b[1]]}">${b[1]}</span><div class="nm"><b>${b[0]}</b><small>${b[2]} · ${b[6]} interest · ${b[4]} left</small></div><div class="y"><b>${b[3].toFixed(2)}%</b><small>yield</small></div><button class="addb" data-login>Invest from ${inr(b[5])}</button></div>`).join('') || '<div class="none">No bonds match this filter.</div>';
          const W = 520, H = 340, pl = 44, pb = 34, X = m => pl + m / 96 * (W - pl - 16), Y = y => H - pb - (y - 7.5) / 4.5 * (H - pb - 16);
          $('#scat').innerHTML = `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Bond yield against time to maturity">${[8, 9, 10, 11].map(y => `<line x1="${pl}" x2="${W - 16}" y1="${Y(y)}" y2="${Y(y)}" stroke="var(--rule)" stroke-dasharray="2 5"/><text x="${pl - 8}" y="${Y(y) + 4}" text-anchor="end" font-size="11" font-weight="600" fill="var(--faint)">${y}%</text>`).join('')}${[0, 2, 4, 6, 8].map(y => `<text x="${X(y * 12)}" y="${H - 10}" text-anchor="middle" font-size="11" font-weight="600" fill="var(--faint)">${y} yrs</text>`).join('')}${B.map(({ b }) => `<g class="bb"><circle cx="${X(b[7])}" cy="${Y(b[3])}" r="${10 + Math.sqrt(b[5]) / 18}" fill="${RC[b[1]]}" fill-opacity=".78" stroke="${RC[b[1]]}" stroke-width="2"><title>${b[0]} · ${b[1]} · ${b[3]}% · ${b[4]}</title></circle></g>`).join('')}</svg>` };
        $('#bdF').onclick = e => { const c = e.target.closest('.chip'); if (!c) return; bf = +c.dataset.f; $$('#bdF .chip').forEach(x => x.setAttribute('aria-pressed', x === c)); bl() }; bl();
        /* deposits */
        let ty = 3, pay = 0; const dp = () => { const a = +$('#dpA').value, r = DEP[ty], m = pay === 0 ? a * Math.pow(1 + r / 400, 4 * ty) : a, g = pay === 0 ? m - a : a * r / 100 * ty; $('#dpAv').textContent = L(a);
          $('#dpLb').textContent = pay === 0 ? `Maturity amount in ${ty} year${ty > 1 ? 's' : ''}` : `${pay === 1 ? 'Quarterly' : 'Monthly'} interest, ${ty} years`;
          $('#dpV').innerHTML = pay === 0 ? L(m) : inr(a * r / 100 / (pay === 1 ? 4 : 12)) + '<small> each ' + (pay === 1 ? 'quarter' : 'month') + '</small>'; $('#dpI').textContent = L(a); $('#dpG').textContent = L(g);
          const s = a * Math.pow(1.03, ty) - a; $('#dpR1').textContent = L(g); $('#dpR2').textContent = L(s); $('#dpB1').style.cssText = `width:${g / Math.max(g, s) * 100}%;background:var(--teal)`; $('#dpB2').style.width = s / Math.max(g, s) * 100 + '%' };
        $('#dpA').oninput = dp; K.fillAll($('#dpS')); $('#dpT').onclick = e => { const c = e.target.closest('.chip'); if (!c) return; ty = +c.dataset.y; $$('#dpT .chip').forEach(x => x.setAttribute('aria-pressed', x === c)); dp() };
        $('#dpP').onclick = e => { const c = e.target.closest('button'); if (!c) return; pay = +c.dataset.p; $$('#dpP button').forEach(x => x.setAttribute('aria-pressed', x === c)); dp() }; dp();
        /* nps */
        let sl = 30; const nps = () => { $('#npsV').textContent = inr(50000 * sl / 100 * 1.04) }; $('#npsS').onclick = e => { const b = e.target.closest('button'); if (!b) return; sl = +b.dataset.s; $$('#npsS button').forEach(x => x.setAttribute('aria-pressed', x === b)); nps() }; nps();
        /* insurance */
        const ins = () => { const i = +$('#inI').value, l = +$('#inL').value, e = +$('#inE').value, c = Math.max(0, 15 * i + l - e); $('#inIv').textContent = '₹' + i + ' L'; $('#inLv').textContent = '₹' + l + ' L'; $('#inEv').textContent = '₹' + e + ' L'; $('#inV').textContent = L(c * 1e5); $('#inX').textContent = (c / i).toFixed(0) + '×' };
        ['#inI', '#inL', '#inE'].forEach(s => $(s).oninput = ins); K.fillAll($('#inS')); ins();
      }
    };
  };

  /* ======================= GOALS ======================= */
  K.pages['/goals'] = (sub) => {
    const gid = (sub || '').split('/')[0] || 'edu', yr0 = new Date().getFullYear();
    const items = [['Child’s college, India', 25, 12, 8], ['College abroad', 80, 12, 9], ['Wedding', 25, 8, 7], ['A home down payment', 30, 6, 7], ['A new car', 12, 4, 5], ['Retirement corpus', 200, 25, 6]];
    const h = `
<section class="ph-hero gh"><div class="w"><span class="eyebrow">Goal planner</span><h1 data-r>Plan for what you <em>actually</em> want.</h1><p class="lede" data-r style="--d:.08s">Pick a goal and see what it will cost by the time you need it, how much to set aside each month, and how we would invest it.</p></div></section>
<section class="sec" style="padding-top:20px"><div class="w">${K.plannerHTML('gp2')}</div></section>

<section class="sec cream"><div class="w"><div class="gpath"><div><span class="eyebrow">The glide path</span><h2 style="margin:18px 0 20px" data-r>Take risk while you have time. <em>Take it off</em> as the date gets closer.</h2><p class="lede" data-r>This is the part most DIY investors skip. For a goal 15 years away, we start mostly in equity. Every year after, a little moves to debt, so a bad market in the final stretch cannot undo the plan.</p>
  <div class="gp-steps">${[['Years 15 to 8', 'Grow', 'Mostly equity. Ignore the noise.'], ['Years 8 to 3', 'Protect', 'Equity trimmed each year.'], ['Last 3 years', 'Secure', 'Mostly debt, so the money is there when the fee is due.']].map((s, i) => `<div data-r style="--d:${i * .08}s"><span class="no">${i + 1}</span><div><small>${s[0]}</small><b>${s[1]}</b><p>${s[2]}</p></div></div>`).join('')}</div></div>
  <div class="gl-c" data-r="rt"><div id="glCh"></div><div class="legend" style="margin-top:12px"><span><i style="background:#12A3AE"></i>Equity</span><span><i style="background:#9AA1D8"></i>Debt</span><span><i style="background:#E8A317"></i>Gold</span></div></div></div></div></section>

<section class="sec"><div class="w"><div class="shead row"><div><span class="eyebrow">What things cost</span><h2 style="margin-top:18px" data-r>Today’s price is <em>not</em> the price you will pay.</h2></div><p class="lede" data-r>Inflation compounds quietly. The pale bar is what it costs today, and the dark bar is what it will cost on the date you need it.</p></div>
  <div class="infl">${items.map((it, i) => { const f = it[1] * Math.pow(1 + it[3] / 100, it[2]), mx = 200 * Math.pow(1.06, 25); return `<div class="ir" data-r style="--d:${i * .05}s"><div class="nm"><b>${it[0]}</b><small>in ${it[2]} years · ${it[3]}% a year</small></div><div class="bars"><i class="a" style="width:${it[1] / mx * 100 + 1.5}%"></i><i class="b" style="width:${f / mx * 100 + 2}%"></i></div><div class="v n"><small>${L(it[1] * 1e5)} →</small><b>${L(f * 1e5)}</b></div></div>` }).join('')}</div></div></section>
${cta('Bring your goals. We will bring the plan.', 'Start my plan')}`;
    return {
      t: 'Goal planner', h, w() {
        K.wirePlanner(gid, 'gp2');
        const eq = [], de = [], go = []; for (let i = 0; i <= 15; i++) { const e = i < 7 ? 70 : i < 12 ? 70 - (i - 6) * 8 : 28 - (i - 11) * 6; eq.push(Math.max(8, e)); go.push(10); de.push(100 - Math.max(8, e) - 10) }
        K.chart($('#glCh'), { h: 300, stack: true, ymax: 100, series: [{ name: 'Equity', data: eq, color: '#12A3AE', fill: 'rgba(18,163,174,.75)' }, { name: 'Debt', data: de, color: '#9AA1D8', fill: 'rgba(154,161,216,.7)' }, { name: 'Gold', data: go, color: '#E8A317', fill: 'rgba(232,163,23,.8)' }], x: i => yr0 + i, tipx: i => 'Year ' + i + ' of 15', fmt: v => Math.round(v) + '%', yfmt: v => v + '%', xticks: 6, total: 'Total' });
      }
    };
  };
})(window.K);
